token: c5372449
name: Black Tie Light
family: Black Tie
style: Light
version: 1.0.0
filename: BlackTie-Light.ttf
optimized_for: 14px
css_prefix: btl
icon_css_prefix: bt
website: http://blacktie.io
premium: false

designer:
  first_name: Dave
  last_name: Gandy
  email: dave@davegandy.com
  website: http://davegandy.com

plans:
  - basic
  - pro
  - owner
  - business10
  - business10_annual
  - business20
  - business20_annual
  - business50
  - business50_annual
  - business100
  - business100_annual

icons:
  - name: 'bars'
    unicode: 'f000'

  - name: 'envelope'
    unicode: 'f001'

  - name: 'search'
    unicode: 'f002'

  - name: 'search-plus'
    unicode: 'f003'

  - name: 'search-minus'
    unicode: 'f004'

  - name: 'phone'
    unicode: 'f005'

  - name: 'comment'
    unicode: 'f007'

  - name: 'commenting'
    unicode: 'f008'

  - name: 'comments'
    unicode: 'f009'

  - name: 'rss'
    unicode: 'f00a'

  - name: 'times'
    unicode: 'f00c'

  - name: 'times-circle'
    unicode: 'f00d'

  - name: 'clock'
    unicode: 'f00e'

  - name: 'star'
    unicode: 'f010'

  - name: 'star-half'
    unicode: 'f011'

  - name: 'check'
    unicode: 'f012'

  - name: 'check-circle'
    unicode: 'f013'

  - name: 'check-square'
    unicode: 'f014'

  - name: 'th'
    unicode: 'f015'

  - name: 'th-large'
    unicode: 'f016'

  - name: 'heart'
    unicode: 'f017'

  - name: 'heart-half'
    unicode: 'f018'

  - name: 'calendar'
    unicode: 'f019'

  - name: 'shopping-cart'
    unicode: 'f01a'

  - name: 'plus'
    unicode: 'f01b'

  - name: 'plus-circle'
    unicode: 'f01c'

  - name: 'plus-square'
    unicode: 'f01d'

  - name: 'pen'
    unicode: 'f01e'

  - name: 'minus'
    unicode: 'f021'

  - name: 'minus-circle'
    unicode: 'f022'

  - name: 'minus-square'
    unicode: 'f023'

  - name: 'pencil'
    unicode: 'f024'

  - name: 'edit'
    unicode: 'f025'

  - name: 'thumbs-up'
    unicode: 'f026'

  - name: 'thumbs-down'
    unicode: 'f027'

  - name: 'gear'
    unicode: 'f028'

  - name: 'trash'
    unicode: 'f029'

  - name: 'file'
    unicode: 'f02a'

  - name: 'info-circle'
    unicode: 'f02b'

  - name: 'label'
    unicode: 'f02c'

  - name: 'rocket'
    unicode: 'f02d'

  - name: 'book'
    unicode: 'f02e'

  - name: 'book-open'
    unicode: 'f02f'

  - name: 'notebook'
    unicode: 'f030'

  - name: 'camera'
    unicode: 'f031'

  - name: 'folder'
    unicode: 'f032'

  - name: 'quote-left'
    unicode: 'f036'

  - name: 'quote-right'
    unicode: 'f037'

  - name: 'eye'
    unicode: 'f038'

  - name: 'lock'
    unicode: 'f039'

  - name: 'lock-open'
    unicode: 'f03a'

  - name: 'gift'
    unicode: 'f03b'

  - name: 'spinner-clock'
    unicode: 'f03c'

  - name: 'spinner'
    unicode: 'f03d'

  - name: 'wrench'
    unicode: 'f03e'

  - name: 'cloud'
    unicode: 'f040'

  - name: 'cloud-upload'
    unicode: 'f041'

  - name: 'cloud-download'
    unicode: 'f042'

  - name: 'sync'
    unicode: 'f043'

  - name: 'question-circle'
    unicode: 'f044'

  - name: 'share'
    unicode: 'f045'

  - name: 'briefcase'
    unicode: 'f046'

  - name: 'money'
    unicode: 'f047'

  - name: 'megaphone'
    unicode: 'f048'

  - name: 'sign-in'
    unicode: 'f049'

  - name: 'sign-out'
    unicode: 'f04a'

  - name: 'film'
    unicode: 'f04b'

  - name: 'trophy'
    unicode: 'f04c'

  - name: 'code'
    unicode: 'f04d'

  - name: 'light-bulb'
    unicode: 'f04e'

  - name: 'print'
    unicode: 'f050'

  - name: 'fax'
    unicode: 'f051'

  - name: 'video'
    unicode: 'f052'

  - name: 'signal'
    unicode: 'f053'

  - name: 'sitemap'
    unicode: 'f054'

  - name: 'upload'
    unicode: 'f055'

  - name: 'download'
    unicode: 'f056'

  - name: 'key'
    unicode: 'f057'

  - name: 'mug'
    unicode: 'f058'

  - name: 'bookmark'
    unicode: 'f059'

  - name: 'flag'
    unicode: 'f05a'

  - name: 'external-link'
    unicode: 'f05b'

  - name: 'smile'
    unicode: 'f05c'

  - name: 'frown'
    unicode: 'f05d'

  - name: 'meh'
    unicode: 'f05e'

  - name: 'magic'
    unicode: 'f060'

  - name: 'bolt'
    unicode: 'f061'

  - name: 'exclamation-triangle'
    unicode: 'f062'

  - name: 'exclamation-circle'
    unicode: 'f063'

  - name: 'flask'
    unicode: 'f064'

  - name: 'music'
    unicode: 'f065'

  - name: 'push-pin'
    unicode: 'f066'

  - name: 'shield'
    unicode: 'f067'

  - name: 'sort'
    unicode: 'f068'

  - name: 'reply'
    unicode: 'f069'

  - name: 'forward'
    unicode: 'f06a'

  - name: 'reply-all'
    unicode: 'f06b'

  - name: 'forward-all'
    unicode: 'f06c'

  - name: 'bell'
    unicode: 'f06d'

  - name: 'bell-off'
    unicode: 'f06e'

  - name: 'ban'
    unicode: 'f070'

  - name: 'database'
    unicode: 'f071'

  - name: 'hard-drive'
    unicode: 'f072'

  - name: 'merge'
    unicode: 'f073'

  - name: 'fork'
    unicode: 'f074'

  - name: 'wifi'
    unicode: 'f075'

  - name: 'paper-plane'
    unicode: 'f076'

  - name: 'inbox'
    unicode: 'f077'

  - name: 'fire'
    unicode: 'f078'

  - name: 'play'
    unicode: 'f079'

  - name: 'pause'
    unicode: 'f07a'

  - name: 'stop'
    unicode: 'f08b'

  - name: 'play-circle'
    unicode: 'f07b'

  - name: 'next'
    unicode: 'f07c'

  - name: 'previous'
    unicode: 'f07d'

  - name: 'repeat'
    unicode: 'f07e'

  - name: 'fast-forward'
    unicode: 'f080'

  - name: 'fast-reverse'
    unicode: 'f081'

  - name: 'volume'
    unicode: 'f082'

  - name: 'volume-off'
    unicode: 'f083'

  - name: 'volume-up'
    unicode: 'f084'

  - name: 'volume-down'
    unicode: 'f085'

  - name: 'maximize'
    unicode: 'f086'

  - name: 'minimize'
    unicode: 'f087'

  - name: 'closed-captions'
    unicode: 'f088'

  - name: 'shuffle'
    unicode: 'f089'

  - name: 'triangle'
    unicode: 'f08a'

  - name: 'square'
    unicode: 'f08b'

  - name: 'circle'
    unicode: 'f08c'

  - name: 'hexagon'
    unicode: 'f08d'

  - name: 'octagon'
    unicode: 'f08e'

  - name: 'angle-up'
    unicode: 'f090'

  - name: 'angle-down'
    unicode: 'f091'

  - name: 'angle-left'
    unicode: 'f092'

  - name: 'angle-right'
    unicode: 'f093'

  - name: 'angles-up'
    unicode: 'f094'

  - name: 'angles-down'
    unicode: 'f095'

  - name: 'angles-left'
    unicode: 'f096'

  - name: 'angles-right'
    unicode: 'f097'

  - name: 'arrow-up'
    unicode: 'f098'

  - name: 'arrow-down'
    unicode: 'f099'

  - name: 'arrow-left'
    unicode: 'f09a'

  - name: 'arrow-right'
    unicode: 'f09b'

  - name: 'bar-chart'
    unicode: 'f09c'

  - name: 'pie-chart'
    unicode: 'f09d'

  - name: 'circle-arrow-up'
    unicode: 'f0a0'

  - name: 'circle-arrow-down'
    unicode: 'f0a1'

  - name: 'circle-arrow-left'
    unicode: 'f0a2'

  - name: 'circle-arrow-right'
    unicode: 'f0a3'

  - name: 'caret-up'
    unicode: 'f0a4'

  - name: 'caret-down'
    unicode: 'f0a5'

  - name: 'caret-left'
    unicode: 'f0a6'

  - name: 'caret-right'
    unicode: 'f0a7'

  - name: 'long-arrow-up'
    unicode: 'f0a8'

  - name: 'long-arrow-down'
    unicode: 'f0a9'

  - name: 'long-arrow-left'
    unicode: 'f0aa'

  - name: 'long-arrow-right'
    unicode: 'f0ab'

  - name: 'bold'
    unicode: 'f0ac'

  - name: 'italic'
    unicode: 'f0ad'

  - name: 'underline'
    unicode: 'f0ae'

  - name: 'link'
    unicode: 'f0b0'

  - name: 'paper-clip'
    unicode: 'f0b1'

  - name: 'align-left'
    unicode: 'f0b2'

  - name: 'align-center'
    unicode: 'f0b3'

  - name: 'align-right'
    unicode: 'f0b4'

  - name: 'align-justify'
    unicode: 'f0b5'

  - name: 'cut'
    unicode: 'f0b6'

  - name: 'copy'
    unicode: 'f0b7'

  - name: 'paste'
    unicode: 'f0b8'

  - name: 'photo'
    unicode: 'f0b9'

  - name: 'table'
    unicode: 'f0ba'

  - name: 'ulist'
    unicode: 'f0bb'

  - name: 'olist'
    unicode: 'f0bc'

  - name: 'indent'
    unicode: 'f0bd'

  - name: 'outdent'
    unicode: 'f0be'

  - name: 'undo'
    unicode: 'f0c0'

  - name: 'redo'
    unicode: 'f0c1'

  - name: 'sup'
    unicode: 'f0c2'

  - name: 'sub'
    unicode: 'f0c3'

  - name: 'text-size'
    unicode: 'f0c4'

  - name: 'text-color'
    unicode: 'f0c5'

  - name: 'remove-formatting'
    unicode: 'f0c6'

  - name: 'blockquote'
    unicode: 'f036'

  - name: 'globe'
    unicode: 'f0c7'

  - name: 'map'
    unicode: 'f0c8'

  - name: 'map-arrow'
    unicode: 'f0c9'

  - name: 'map-marker'
    unicode: 'f0ca'

  - name: 'map-pin'
    unicode: 'f0cb'

  - name: 'home'
    unicode: 'f0cc'

  - name: 'building'
    unicode: 'f0cd'

  - name: 'industry'
    unicode: 'f0ce'

  - name: 'desktop'
    unicode: 'f0d0'

  - name: 'laptop'
    unicode: 'f0d1'

  - name: 'tablet'
    unicode: 'f0d2'

  - name: 'mobile'
    unicode: 'f0d3'

  - name: 'tv'
    unicode: 'f0d4'

  - name: 'radio-checked'
    unicode: 'f0d5'

  - name: 'radio-unchecked'
    unicode: 'f08c'

  - name: 'checkbox-checked'
    unicode: 'f014'

  - name: 'checkbox-unchecked'
    unicode: 'f08b'

  - name: 'checkbox-intermediate'
    unicode: 'f023'

  - name: 'user'
    unicode: 'f0d6'

  - name: 'user-male'
    unicode: 'f0d6'

  - name: 'user-female'
    unicode: 'f0d7'

  - name: 'crown'
    unicode: 'f0d8'

  - name: 'credit-card'
    unicode: 'f0d9'

  - name: 'strikethrough'
    unicode: 'f0da'

  - name: 'eject'
    unicode: 'f0db'

  - name: 'ellipsis-h'
    unicode: 'f0dc'

  - name: 'ellipsis-v'
    unicode: 'f0dd'
