token: e98234ee
name: Smarticons Outline
family: Smarticons Outline
style: Regular
weight: Regular
version: 1.0.0
filename: SmarticonsOutline.otf
optimized_for: 64px
css_prefix: si-outline
icon_css_prefix: si-outline
website: https://smarticons.co/all/set/outline
premium: true
price: 25.00
download_package: si-outline.zip
active: false

foundry:
  name: Smarticons
  email: info@smarticons.co
  website: https://smarticons.co

plans:
  - owner

icons:
- name: 35mm-film
  unicode: f000
- name: acoustic-guitar
  unicode: f001
- name: adjustment-horizol
  unicode: f002
- name: adjustment-vertical
  unicode: f003
- name: airplane
  unicode: f004
- name: alarm-clock
  unicode: f005
- name: alien
  unicode: f006
- name: ambulancer
  unicode: f007
- name: anchor
  unicode: f008
- name: arrow-big-bottom-left
  unicode: f009
- name: arrow-big-bottom-right
  unicode: f00a
- name: arrow-big-down
  unicode: f00b
- name: arrow-big-four-way-1
  unicode: f00c
- name: arrow-big-four-way-2
  unicode: f00d
- name: arrow-big-left-right
  unicode: f00e
- name: arrow-big-left
  unicode: f00f
- name: arrow-big-right-bottom
  unicode: f010
- name: arrow-big-right
  unicode: f011
- name: arrow-big-three-ways
  unicode: f012
- name: arrow-big-top-left
  unicode: f013
- name: arrow-big-top-right
  unicode: f014
- name: arrow-big-two-way-left-right
  unicode: f015
- name: arrow-big-two-way-up-down
  unicode: f016
- name: arrow-big-up-down
  unicode: f017
- name: arrow-big-up
  unicode: f018
- name: atm-card
  unicode: f019
- name: atomic
  unicode: f01a
- name: baby-stroller
  unicode: f01b
- name: bag-add
  unicode: f01c
- name: bag-check
  unicode: f01d
- name: bag-down
  unicode: f01e
- name: bag-heart
  unicode: f01f
- name: bag-next
  unicode: f020
- name: bag-previous
  unicode: f021
- name: bag-remove
  unicode: f022
- name: bag-up
  unicode: f023
- name: bag
  unicode: f024
- name: balloon
  unicode: f025
- name: bank
  unicode: f026
- name: barrier
  unicode: f027
- name: base-ball
  unicode: f028
- name: battery-charging
  unicode: f029
- name: battery-empty
  unicode: f02a
- name: battery-full
  unicode: f02b
- name: battery-half
  unicode: f02c
- name: battery-low
  unicode: f02d
- name: beer
  unicode: f02e
- name: bell
  unicode: f02f
- name: billard
  unicode: f030
- name: birthday-cake
  unicode: f031
- name: bluetooth
  unicode: f032
- name: boat
  unicode: f033
- name: bolt
  unicode: f034
- name: bomb
  unicode: f035
- name: book-bookmark
  unicode: f036
- name: book-open
  unicode: f037
- name: book
  unicode: f038
- name: bottle
  unicode: f039
- name: bowl
  unicode: f03a
- name: bowling
  unicode: f03b
- name: box
  unicode: f03c
- name: bread
  unicode: f03d
- name: briefcase
  unicode: f03e
- name: brush
  unicode: f03f
- name: building
  unicode: f040
- name: bus
  unicode: f041
- name: button-circle-at
  unicode: f042
- name: button-circle-add
  unicode: f043
- name: button-circle-arrow-add
  unicode: f044
- name: button-circle-arrow-down
  unicode: f045
- name: button-circle-arrow-right
  unicode: f046
- name: button-circle-checked
  unicode: f047
- name: button-circle-delete
  unicode: f048
- name: button-circle-download
  unicode: f049
- name: button-circle-heart
  unicode: f04a
- name: button-circle-next
  unicode: f04b
- name: button-circle-paurse
  unicode: f04c
- name: button-circle-person
  unicode: f04d
- name: button-circle-previous
  unicode: f04e
- name: button-circle-remove
  unicode: f04f
- name: button-circle-star
  unicode: f050
- name: button-circle-triangle-down
  unicode: f051
- name: button-circle-triangle-left
  unicode: f052
- name: button-circle-triangle-right
  unicode: f053
- name: button-circle-triangle-up
  unicode: f054
- name: button-circle-upload
  unicode: f055
- name: button-circle-warning
  unicode: f056
- name: button-stop
  unicode: f057
- name: cabinet
  unicode: f058
- name: calendar
  unicode: f059
- name: call-error
  unicode: f05a
- name: call-forward
  unicode: f05b
- name: call-reply
  unicode: f05c
- name: camera
  unicode: f05d
- name: candle
  unicode: f05e
- name: canvas
  unicode: f05f
- name: car
  unicode: f060
- name: cart-add
  unicode: f061
- name: cart-checked
  unicode: f062
- name: cart-download
  unicode: f063
- name: cart-heart
  unicode: f064
- name: cart-remove
  unicode: f065
- name: cart-upload
  unicode: f066
- name: cart
  unicode: f067
- name: cash-dollar
  unicode: f068
- name: cash-euro
  unicode: f069
- name: cash-yen
  unicode: f06a
- name: cashier-machine
  unicode: f06b
- name: cassette
  unicode: f06c
- name: cat
  unicode: f06d
- name: chair
  unicode: f06e
- name: char-column-1
  unicode: f06f
- name: chart-column-2
  unicode: f070
- name: chat-bubble
  unicode: f071
- name: chemistry
  unicode: f072
- name: cherry
  unicode: f073
- name: chicken-leg
  unicode: f074
- name: chimney
  unicode: f075
- name: christmas-tree
  unicode: f076
- name: church
  unicode: f077
- name: circle
  unicode: f078
- name: clap-board
  unicode: f079
- name: clipboard-checked
  unicode: f07a
- name: clipboard-edit
  unicode: f07b
- name: clipboard
  unicode: f07c
- name: cloud-add
  unicode: f07d
- name: cloud-arrow-left
  unicode: f07e
- name: cloud-arrow-right
  unicode: f07f
- name: cloud-checked
  unicode: f080
- name: cloud-delete
  unicode: f081
- name: cloud-download
  unicode: f082
- name: cloud-reload
  unicode: f083
- name: cloud-remove
  unicode: f084
- name: cloud-upload
  unicode: f085
- name: cloud
  unicode: f086
- name: coffee-cup
  unicode: f087
- name: coffin
  unicode: f088
- name: cog
  unicode: f089
- name: color-palette
  unicode: f08a
- name: compass
  unicode: f08b
- name: compasses
  unicode: f08c
- name: competition
  unicode: f08d
- name: cone
  unicode: f08e
- name: constroller
  unicode: f08f
- name: contact-book-1
  unicode: f090
- name: contact-book-2
  unicode: f091
- name: conversation
  unicode: f092
- name: cooking
  unicode: f093
- name: crop
  unicode: f094
- name: crown
  unicode: f095
- name: cup
  unicode: f096
- name: dashboard
  unicode: f097
- name: database-add
  unicode: f098
- name: database-checked
  unicode: f099
- name: database-download
  unicode: f09a
- name: database-error
  unicode: f09b
- name: database-next
  unicode: f09c
- name: database-previous
  unicode: f09d
- name: database-remove
  unicode: f09e
- name: database-upload
  unicode: f09f
- name: database
  unicode: f0a0
- name: deny
  unicode: f0a1
- name: diamond
  unicode: f0a2
- name: disc-add
  unicode: f0a3
- name: disc-checked
  unicode: f0a4
- name: disc-download
  unicode: f0a5
- name: disc-heart
  unicode: f0a6
- name: disc-paurse
  unicode: f0a7
- name: disc-play
  unicode: f0a8
- name: disc-remove
  unicode: f0a9
- name: disc-stop
  unicode: f0aa
- name: disc-upload
  unicode: f0ab
- name: disc
  unicode: f0ac
- name: display
  unicode: f0ad
- name: dna
  unicode: f0ae
- name: document-add
  unicode: f0af
- name: document-checklist
  unicode: f0b0
- name: document-coppy
  unicode: f0b1
- name: document-download
  unicode: f0b2
- name: document-edit
  unicode: f0b3
- name: document-empty
  unicode: f0b4
- name: document-error
  unicode: f0b5
- name: document-heart
  unicode: f0b6
- name: document-locked
  unicode: f0b7
- name: document-next
  unicode: f0b8
- name: document-previous
  unicode: f0b9
- name: document-remove
  unicode: f0ba
- name: document-signal
  unicode: f0bb
- name: document-star
  unicode: f0bc
- name: document-upload
  unicode: f0bd
- name: document
  unicode: f0be
- name: dog
  unicode: f0bf
- name: dress
  unicode: f0c0
- name: driller
  unicode: f0c1
- name: drum
  unicode: f0c2
- name: egg-1
  unicode: f0c3
- name: egg-2
  unicode: f0c4
- name: enlarge
  unicode: f0c5
- name: evelator-down
  unicode: f0c6
- name: evelator-up
  unicode: f0c7
- name: eye
  unicode: f0c8
- name: eyedropper
  unicode: f0c9
- name: factory
  unicode: f0ca
- name: fan
  unicode: f0cb
- name: faucet
  unicode: f0cc
- name: feather
  unicode: f0cd
- name: female
  unicode: f0ce
- name: fence
  unicode: f0cf
- name: film
  unicode: f0d0
- name: filter
  unicode: f0d1
- name: fire-alarm
  unicode: f0d2
- name: fire-extinguisher
  unicode: f0d3
- name: fire
  unicode: f0d4
- name: fish-bone
  unicode: f0d5
- name: flag
  unicode: f0d6
- name: flip-flop
  unicode: f0d7
- name: floppy-disc
  unicode: f0d8
- name: folder-at
  unicode: f0d9
- name: folder-add
  unicode: f0da
- name: folder-checked
  unicode: f0db
- name: folder-download
  unicode: f0dc
- name: folder-error
  unicode: f0dd
- name: folder-next
  unicode: f0de
- name: folder-open
  unicode: f0df
- name: folder-previous
  unicode: f0e0
- name: folder-remove
  unicode: f0e1
- name: folder-search
  unicode: f0e2
- name: folder-share
  unicode: f0e3
- name: folder-signal
  unicode: f0e4
- name: folder-upload
  unicode: f0e5
- name: folder
  unicode: f0e6
- name: food-cover
  unicode: f0e7
- name: game-boy
  unicode: f0e8
- name: gas-station
  unicode: f0e9
- name: gift
  unicode: f0ea
- name: glasses
  unicode: f0eb
- name: globe-pin-location
  unicode: f0ec
- name: globe
  unicode: f0ed
- name: hack
  unicode: f0ee
- name: hammer
  unicode: f0ef
- name: hand-finger
  unicode: f0f0
- name: hanger
  unicode: f0f1
- name: headset
  unicode: f0f2
- name: heart-add
  unicode: f0f3
- name: heart-remove
  unicode: f0f4
- name: heart-signal
  unicode: f0f5
- name: heart
  unicode: f0f6
- name: horse-shoe
  unicode: f0f7
- name: hour-glass
  unicode: f0f8
- name: house-dollar
  unicode: f0f9
- name: house
  unicode: f0fa
- name: humberger
  unicode: f0fb
- name: ice-cream-1
  unicode: f0fc
- name: ice-cream-2
  unicode: f0fd
- name: inbox-download
  unicode: f0fe
- name: inbox-upload
  unicode: f0ff
- name: inbox
  unicode: f100
- name: iphone
  unicode: f101
- name: iron
  unicode: f102
- name: joystick
  unicode: f103
- name: jupiter
  unicode: f104
- name: key
  unicode: f105
- name: keyboard
  unicode: f106
- name: ladder
  unicode: f107
- name: lamp-desk
  unicode: f108
- name: laptop
  unicode: f109
- name: law
  unicode: f10a
- name: life-jacket
  unicode: f10b
- name: life-saver
  unicode: f10c
- name: light-bulb
  unicode: f10d
- name: light-house
  unicode: f10e
- name: limit-left
  unicode: f10f
- name: limit-right
  unicode: f110
- name: line-chart-decrease
  unicode: f111
- name: line-chart-increase
  unicode: f112
- name: link
  unicode: f113
- name: location
  unicode: f114
- name: lock-unlock
  unicode: f115
- name: lock
  unicode: f116
- name: login
  unicode: f117
- name: logout
  unicode: f118
- name: loud-speaker
  unicode: f119
- name: magnet
  unicode: f11a
- name: magnifier-zoom-in
  unicode: f11b
- name: magnifier-zoom-out
  unicode: f11c
- name: magnifier
  unicode: f11d
- name: mail-backward
  unicode: f11e
- name: mail-checked
  unicode: f11f
- name: mail-download
  unicode: f120
- name: mail-empty
  unicode: f121
- name: mail-forward
  unicode: f122
- name: mail-has-mail
  unicode: f123
- name: mail-upload
  unicode: f124
- name: mail
  unicode: f125
- name: male
  unicode: f126
- name: map-pin-location
  unicode: f127
- name: mask
  unicode: f128
- name: meat
  unicode: f129
- name: medal
  unicode: f12a
- name: medicine-pot
  unicode: f12b
- name: medicine
  unicode: f12c
- name: message-dot
  unicode: f12d
- name: message-text
  unicode: f12e
- name: microphone-1
  unicode: f12f
- name: microphone-2
  unicode: f130
- name: microphone-mute
  unicode: f131
- name: microscope
  unicode: f132
- name: mill
  unicode: f133
- name: molecule
  unicode: f134
- name: money-bag-dollar
  unicode: f135
- name: money-bag-euro
  unicode: f136
- name: money-bag-pound
  unicode: f137
- name: moon-stars
  unicode: f138
- name: moon
  unicode: f139
- name: mountain-volcano
  unicode: f13a
- name: mountains
  unicode: f13b
- name: movie
  unicode: f13c
- name: mushroom
  unicode: f13d
- name: musical-note
  unicode: f13e
- name: mustache
  unicode: f13f
- name: network-1
  unicode: f140
- name: network-2
  unicode: f141
- name: network-3
  unicode: f142
- name: network
  unicode: f143
- name: newspaper
  unicode: f144
- name: next
  unicode: f145
- name: nuclear
  unicode: f146
- name: oxygen
  unicode: f147
- name: paper-clip
  unicode: f148
- name: paper-plane
  unicode: f149
- name: paragraph
  unicode: f14a
- name: pawn
  unicode: f14b
- name: pen
  unicode: f14c
- name: pencil
  unicode: f14d
- name: person-add
  unicode: f14e
- name: person-checked
  unicode: f14f
- name: person-conversation
  unicode: f150
- name: person-download
  unicode: f151
- name: person-error
  unicode: f152
- name: person-gears
  unicode: f153
- name: person-heart
  unicode: f154
- name: person-next
  unicode: f155
- name: person-previous
  unicode: f156
- name: person-remove
  unicode: f157
- name: person-search
  unicode: f158
- name: person-sideway
  unicode: f159
- name: person-upload
  unicode: f15a
- name: person
  unicode: f15b
- name: persons
  unicode: f15c
- name: phone-book
  unicode: f15d
- name: phone-booth
  unicode: f15e
- name: phone-call
  unicode: f15f
- name: phone-old
  unicode: f160
- name: phone
  unicode: f161
- name: picture
  unicode: f162
- name: pictures
  unicode: f163
- name: piece-chart
  unicode: f164
- name: pill
  unicode: f165
- name: pin-location-add
  unicode: f166
- name: pin-location-checked
  unicode: f167
- name: pin-location-error
  unicode: f168
- name: pin-location-heart
  unicode: f169
- name: pin-location-house
  unicode: f16a
- name: pin-location-point
  unicode: f16b
- name: pin-location-remove
  unicode: f16c
- name: pin-location-star
  unicode: f16d
- name: pin-location
  unicode: f16e
- name: pin
  unicode: f16f
- name: ping-pong
  unicode: f170
- name: pizza-slide
  unicode: f171
- name: playlist
  unicode: f172
- name: plug
  unicode: f173
- name: pocket-bag
  unicode: f174
- name: previous
  unicode: f175
- name: printer
  unicode: f176
- name: puzzle
  unicode: f177
- name: radio
  unicode: f178
- name: recycle
  unicode: f179
- name: rgb
  unicode: f17a
- name: rice-cooker
  unicode: f17b
- name: road-sign-right
  unicode: f17c
- name: road-sign-two-way
  unicode: f17d
- name: road
  unicode: f17e
- name: rocket
  unicode: f17f
- name: roller
  unicode: f180
- name: rugby-ball
  unicode: f181
- name: saver-box
  unicode: f182
- name: scale
  unicode: f183
- name: scissors
  unicode: f184
- name: scooter
  unicode: f185
- name: screw-driver
  unicode: f186
- name: sd-card
  unicode: f187
- name: seriff
  unicode: f188
- name: sewing-machine
  unicode: f189
- name: shake-hand
  unicode: f18a
- name: shield-check
  unicode: f18b
- name: shield-cross
  unicode: f18c
- name: shield
  unicode: f18d
- name: shirt-tie
  unicode: f18e
- name: shoe
  unicode: f18f
- name: shopping-bag
  unicode: f190
- name: short
  unicode: f191
- name: shovel
  unicode: f192
- name: signal
  unicode: f193
- name: sitemap-reverse
  unicode: f194
- name: sitemap
  unicode: f195
- name: skull
  unicode: f196
- name: slideshow-chart
  unicode: f197
- name: slideshow
  unicode: f198
- name: sock
  unicode: f199
- name: sofa
  unicode: f19a
- name: speaker-decrease
  unicode: f19b
- name: speaker-full
  unicode: f19c
- name: speaker-increase
  unicode: f19d
- name: speaker-louder
  unicode: f19e
- name: speaker-low
  unicode: f19f
- name: speaker-mute
  unicode: f1a0
- name: speaker
  unicode: f1a1
- name: spider-net
  unicode: f1a2
- name: square
  unicode: f1a3
- name: stack
  unicode: f1a4
- name: stamp
  unicode: f1a5
- name: star
  unicode: f1a6
- name: steering-wheel
  unicode: f1a7
- name: stethoscope
  unicode: f1a8
- name: store
  unicode: f1a9
- name: suitcase
  unicode: f1aa
- name: sun
  unicode: f1ab
- name: swimming-ladder
  unicode: f1ac
- name: sync
  unicode: f1ad
- name: syringe
  unicode: f1ae
- name: tablet
  unicode: f1af
- name: tag-plus-one
  unicode: f1b0
- name: tag-price
  unicode: f1b1
- name: tag-sale
  unicode: f1b2
- name: tag
  unicode: f1b3
- name: teeth
  unicode: f1b4
- name: television
  unicode: f1b5
- name: temperature
  unicode: f1b6
- name: tent-1
  unicode: f1b7
- name: tent-2
  unicode: f1b8
- name: thumb-down
  unicode: f1b9
- name: thumb-up
  unicode: f1ba
- name: tie
  unicode: f1bb
- name: timer
  unicode: f1bc
- name: toaster
  unicode: f1bd
- name: toilet-paper
  unicode: f1be
- name: tool
  unicode: f1bf
- name: torch
  unicode: f1c0
- name: train
  unicode: f1c1
- name: trash
  unicode: f1c2
- name: triangle-down
  unicode: f1c3
- name: triangle-left
  unicode: f1c4
- name: triangle-right
  unicode: f1c5
- name: triangle-up
  unicode: f1c6
- name: trompet
  unicode: f1c7
- name: truck
  unicode: f1c8
- name: tshirt
  unicode: f1c9
- name: tulip
  unicode: f1ca
- name: two-column
  unicode: f1cb
- name: umbrella
  unicode: f1cc
- name: underwear
  unicode: f1cd
- name: usb
  unicode: f1ce
- name: valley-ball
  unicode: f1cf
- name: van
  unicode: f1d0
- name: vinyl-player
  unicode: f1d1
- name: wacom-tablet
  unicode: f1d2
- name: wall
  unicode: f1d3
- name: wallet
  unicode: f1d4
- name: washing-machine
  unicode: f1d5
- name: watch
  unicode: f1d6
- name: wave-signal-1
  unicode: f1d7
- name: wave-signal-2
  unicode: f1d8
- name: weather-cloud-bolt-rain
  unicode: f1d9
- name: weather-cloud-heavy-rain
  unicode: f1da
- name: weather-cloud-moon
  unicode: f1db
- name: weather-cloud-more-snow
  unicode: f1dc
- name: weather-cloud-rain
  unicode: f1dd
- name: weather-cloud-rainbow
  unicode: f1de
- name: weather-cloud-snow
  unicode: f1df
- name: weather-cloud-storm
  unicode: f1e0
- name: weather-cloud-sun-rain
  unicode: f1e1
- name: weather-cloud-sun-snow
  unicode: f1e2
- name: weather-cloud-sun
  unicode: f1e3
- name: weather-cloud-wind
  unicode: f1e4
- name: weather-clouds-bolt-rain
  unicode: f1e5
- name: weather-clouds-moon
  unicode: f1e6
- name: weather-clouds-rain
  unicode: f1e7
- name: weather-clouds-snow
  unicode: f1e8
- name: weather-clouds
  unicode: f1e9
- name: weather-storm
  unicode: f1ea
- name: weather-wind
  unicode: f1eb
- name: webcame
  unicode: f1ec
- name: weight
  unicode: f1ed
- name: wheel-barrow
  unicode: f1ee
- name: wifi
  unicode: f1ef
- name: wine-glass
  unicode: f1f0
- name: woman-hat
  unicode: f1f1
- name: wrench
  unicode: f1f2
- name: yacth
  unicode: f1f3
- name: zeppelin
  unicode: f1f4
