token: 7786c2fc
name: Smarticons Duo
family: Smarticons Duo
style: Regular
weight: Regular
version: 1.0.0
filename: SmarticonsDuo.otf
optimized_for: 64px
css_prefix: si-duo
icon_css_prefix: si-duo
website: https://smarticons.co/all/set/duo
premium: true
price: 25.00
download_package: si-duo.zip
active: false

foundry:
  name: Smarticons
  email: info@smarticons.co
  website: https://smarticons.co

plans:
  - owner

icons:
- name: 35mm-film
  unicode: f000
- name: adhesive-bandage
  unicode: f001
- name: adjustment-board-horizon
  unicode: f002
- name: adjustment-board-vertical
  unicode: f003
- name: adn
  unicode: f004
- name: airplane
  unicode: f005
- name: alarm-clock
  unicode: f006
- name: ambulance
  unicode: f007
- name: analog-stereo-reel
  unicode: f008
- name: anchor
  unicode: f009
- name: arrow-down
  unicode: f00a
- name: arrow-end-page
  unicode: f00b
- name: arrow-fork
  unicode: f00c
- name: arrow-home-page
  unicode: f00d
- name: arrow-left
  unicode: f00e
- name: arrow-right
  unicode: f00f
- name: arrow-shuffle
  unicode: f010
- name: arrow-two-way-down-up
  unicode: f011
- name: arrow-two-way-left-right
  unicode: f012
- name: arrow-two-way-left
  unicode: f013
- name: arrow-two-way-right
  unicode: f014
- name: arrow-up
  unicode: f015
- name: arrow
  unicode: f016
- name: atm-card
  unicode: f017
- name: atomic
  unicode: f018
- name: backpack
  unicode: f019
- name: bag
  unicode: f01a
- name: balance
  unicode: f01b
- name: bank
  unicode: f01c
- name: barrier
  unicode: f01d
- name: basket-add
  unicode: f01e
- name: basket-checked
  unicode: f01f
- name: basket-delete
  unicode: f020
- name: basket-heart
  unicode: f021
- name: basket-next
  unicode: f022
- name: basket-previous
  unicode: f023
- name: basket-remove
  unicode: f024
- name: basket
  unicode: f025
- name: bath-tube
  unicode: f026
- name: battery-charging
  unicode: f027
- name: battery-full
  unicode: f028
- name: battery-half
  unicode: f029
- name: battery-low
  unicode: f02a
- name: beer
  unicode: f02b
- name: bell-mute
  unicode: f02c
- name: bell-ring
  unicode: f02d
- name: bell-sleep
  unicode: f02e
- name: bell
  unicode: f02f
- name: bicycle
  unicode: f030
- name: birthday-cake
  unicode: f031
- name: bluetooth
  unicode: f032
- name: boat-1
  unicode: f033
- name: boat-2
  unicode: f034
- name: book-at
  unicode: f035
- name: book-person
  unicode: f036
- name: book-rss
  unicode: f037
- name: book
  unicode: f038
- name: bookmark-add
  unicode: f039
- name: bookmark-delete
  unicode: f03a
- name: bookmark-remove
  unicode: f03b
- name: bookmark
  unicode: f03c
- name: boot
  unicode: f03d
- name: bottle
  unicode: f03e
- name: bow
  unicode: f03f
- name: box-download
  unicode: f040
- name: box-empty
  unicode: f041
- name: box-full
  unicode: f042
- name: box-upload
  unicode: f043
- name: box
  unicode: f044
- name: briefcase
  unicode: f045
- name: brightness
  unicode: f046
- name: brush
  unicode: f047
- name: bucket
  unicode: f048
- name: bug
  unicode: f049
- name: building
  unicode: f04a
- name: button-arrow-down
  unicode: f04b
- name: button-arrow-left
  unicode: f04c
- name: button-arrow-right
  unicode: f04d
- name: button-arrow-up
  unicode: f04e
- name: button-dot
  unicode: f04f
- name: cabinet
  unicode: f050
- name: cake
  unicode: f051
- name: calculator
  unicode: f052
- name: calendar
  unicode: f053
- name: call-add
  unicode: f054
- name: call-backward
  unicode: f055
- name: call-delete
  unicode: f056
- name: call-forward
  unicode: f057
- name: call-mute
  unicode: f058
- name: call
  unicode: f059
- name: camera-security
  unicode: f05a
- name: camera
  unicode: f05b
- name: candle
  unicode: f05c
- name: car
  unicode: f05d
- name: caravan
  unicode: f05e
- name: cash
  unicode: f05f
- name: cassette
  unicode: f060
- name: castle
  unicode: f061
- name: chart-1
  unicode: f062
- name: chart-2
  unicode: f063
- name: chart-3
  unicode: f064
- name: chart-4
  unicode: f065
- name: chart-down
  unicode: f066
- name: chart-piece
  unicode: f067
- name: chart-up
  unicode: f068
- name: chef-hat
  unicode: f069
- name: christmas-ball
  unicode: f06a
- name: circle-add
  unicode: f06b
- name: circle-adjustment
  unicode: f06c
- name: circle-arrow-bottom-left
  unicode: f06d
- name: circle-arrow-bottom-right
  unicode: f06e
- name: circle-arrow-down
  unicode: f06f
- name: circle-arrow-left
  unicode: f070
- name: circle-arrow-right
  unicode: f071
- name: circle-arrow-top-left
  unicode: f072
- name: circle-arrow-top-right
  unicode: f073
- name: circle-arrow-up
  unicode: f074
- name: circle-checked
  unicode: f075
- name: circle-delete
  unicode: f076
- name: circle-dollar
  unicode: f077
- name: circle-down
  unicode: f078
- name: circle-euro
  unicode: f079
- name: circle-gear
  unicode: f07a
- name: circle-heart
  unicode: f07b
- name: circle-help
  unicode: f07c
- name: circle-next
  unicode: f07d
- name: circle-paragraph-align-center
  unicode: f07e
- name: circle-paragraph-align-left
  unicode: f07f
- name: circle-paragraph-align-middle
  unicode: f080
- name: circle-paragraph-align-right
  unicode: f081
- name: circle-person
  unicode: f082
- name: circle-previous
  unicode: f083
- name: circle-reload
  unicode: f084
- name: circle-remove
  unicode: f085
- name: circle-star
  unicode: f086
- name: circle-up
  unicode: f087
- name: circle-yen
  unicode: f088
- name: clapboard
  unicode: f089
- name: clipboard
  unicode: f08a
- name: clock
  unicode: f08b
- name: cloud-add
  unicode: f08c
- name: cloud-checked
  unicode: f08d
- name: cloud-delete
  unicode: f08e
- name: cloud-download
  unicode: f08f
- name: cloud-next
  unicode: f090
- name: cloud-previous
  unicode: f091
- name: cloud-reload
  unicode: f092
- name: cloud-upload
  unicode: f093
- name: cloud
  unicode: f094
- name: code
  unicode: f095
- name: coffee-cup
  unicode: f096
- name: color-drop
  unicode: f097
- name: column
  unicode: f098
- name: compass
  unicode: f099
- name: compasses
  unicode: f09a
- name: competition
  unicode: f09b
- name: cone
  unicode: f09c
- name: contrast
  unicode: f09d
- name: coppy
  unicode: f09e
- name: cover-cook
  unicode: f09f
- name: cover-flow
  unicode: f0a0
- name: crop
  unicode: f0a1
- name: crosshair
  unicode: f0a2
- name: crown
  unicode: f0a3
- name: cup
  unicode: f0a4
- name: dashboard
  unicode: f0a5
- name: database-add
  unicode: f0a6
- name: database-checked
  unicode: f0a7
- name: database-delete
  unicode: f0a8
- name: database-download
  unicode: f0a9
- name: database-edit
  unicode: f0aa
- name: database-next
  unicode: f0ab
- name: database-previous
  unicode: f0ac
- name: database-remove
  unicode: f0ad
- name: database-search
  unicode: f0ae
- name: database-upload
  unicode: f0af
- name: database
  unicode: f0b0
- name: deny
  unicode: f0b1
- name: dial-number
  unicode: f0b2
- name: diamond
  unicode: f0b3
- name: disc-add
  unicode: f0b4
- name: disc-checked
  unicode: f0b5
- name: disc-delete
  unicode: f0b6
- name: disc-down
  unicode: f0b7
- name: disc-heart
  unicode: f0b8
- name: disc-list
  unicode: f0b9
- name: disc-music-note
  unicode: f0ba
- name: disc-next
  unicode: f0bb
- name: disc-previous
  unicode: f0bc
- name: disc-remove
  unicode: f0bd
- name: disc-up
  unicode: f0be
- name: disc
  unicode: f0bf
- name: display
  unicode: f0c0
- name: document-at
  unicode: f0c1
- name: document-add
  unicode: f0c2
- name: document-checked
  unicode: f0c3
- name: document-copy
  unicode: f0c4
- name: document-delete
  unicode: f0c5
- name: document-down
  unicode: f0c6
- name: document-edit
  unicode: f0c7
- name: document-file
  unicode: f0c8
- name: document-help
  unicode: f0c9
- name: document-info
  unicode: f0ca
- name: document-lock
  unicode: f0cb
- name: document-next
  unicode: f0cc
- name: document-previous
  unicode: f0cd
- name: document-remove
  unicode: f0ce
- name: document-rss
  unicode: f0cf
- name: document-search
  unicode: f0d0
- name: document-up
  unicode: f0d1
- name: document
  unicode: f0d2
- name: dollar-money
  unicode: f0d3
- name: door
  unicode: f0d4
- name: down-stair
  unicode: f0d5
- name: drop-water
  unicode: f0d6
- name: easel-chart
  unicode: f0d7
- name: easel
  unicode: f0d8
- name: entrance
  unicode: f0d9
- name: euro-money
  unicode: f0da
- name: eyes
  unicode: f0db
- name: factory
  unicode: f0dc
- name: feather
  unicode: f0dd
- name: feet
  unicode: f0de
- name: female
  unicode: f0df
- name: fence
  unicode: f0e0
- name: file-download
  unicode: f0e1
- name: file-upload
  unicode: f0e2
- name: film-strip-play
  unicode: f0e3
- name: film
  unicode: f0e4
- name: fire
  unicode: f0e5
- name: fish
  unicode: f0e6
- name: flag
  unicode: f0e7
- name: flashlight
  unicode: f0e8
- name: floppy-disk
  unicode: f0e9
- name: flower
  unicode: f0ea
- name: folder-at
  unicode: f0eb
- name: folder-add
  unicode: f0ec
- name: folder-checked
  unicode: f0ed
- name: folder-delete
  unicode: f0ee
- name: folder-download
  unicode: f0ef
- name: folder-help
  unicode: f0f0
- name: folder-info
  unicode: f0f1
- name: folder-lock
  unicode: f0f2
- name: folder-next
  unicode: f0f3
- name: folder-open
  unicode: f0f4
- name: folder-previous
  unicode: f0f5
- name: folder-remove
  unicode: f0f6
- name: folder-rss
  unicode: f0f7
- name: folder-search
  unicode: f0f8
- name: folder-share
  unicode: f0f9
- name: folder-upload
  unicode: f0fa
- name: folder
  unicode: f0fb
- name: fork-knife
  unicode: f0fc
- name: forward
  unicode: f0fd
- name: four-arrow-center
  unicode: f0fe
- name: fridge
  unicode: f0ff
- name: full-screen
  unicode: f100
- name: fullscreen-2
  unicode: f101
- name: game-2
  unicode: f102
- name: gameboy
  unicode: f103
- name: garage
  unicode: f104
- name: gas-station
  unicode: f105
- name: gear
  unicode: f106
- name: ghost
  unicode: f107
- name: gift
  unicode: f108
- name: glass-hour
  unicode: f109
- name: glass
  unicode: f10a
- name: glasses
  unicode: f10b
- name: global
  unicode: f10c
- name: graduation-cap
  unicode: f10d
- name: grid
  unicode: f10e
- name: group
  unicode: f10f
- name: hammer
  unicode: f110
- name: hand-finger-left
  unicode: f111
- name: hand-finger-right
  unicode: f112
- name: hand-finger-touch
  unicode: f113
- name: hand-finger-up
  unicode: f114
- name: hand
  unicode: f115
- name: hanger
  unicode: f116
- name: headset
  unicode: f117
- name: heart-broken
  unicode: f118
- name: heart-signal
  unicode: f119
- name: history
  unicode: f11a
- name: hospital
  unicode: f11b
- name: house
  unicode: f11c
- name: ice-cream
  unicode: f11d
- name: inbox
  unicode: f11e
- name: ipod
  unicode: f11f
- name: kayak
  unicode: f120
- name: key
  unicode: f121
- name: keyboard
  unicode: f122
- name: knife
  unicode: f123
- name: laptop
  unicode: f124
- name: law
  unicode: f125
- name: leaf
  unicode: f126
- name: life-saver
  unicode: f127
- name: light-house
  unicode: f128
- name: lightbulb
  unicode: f129
- name: link
  unicode: f12a
- name: lock
  unicode: f12b
- name: loudspeaker
  unicode: f12c
- name: magnifier
  unicode: f12d
- name: mail-empty
  unicode: f12e
- name: mail-forward
  unicode: f12f
- name: mail-has-mail
  unicode: f130
- name: mail-previous
  unicode: f131
- name: mail
  unicode: f132
- name: male
  unicode: f133
- name: map
  unicode: f134
- name: mask
  unicode: f135
- name: medal-star
  unicode: f136
- name: medal
  unicode: f137
- name: menu-board
  unicode: f138
- name: message-dot
  unicode: f139
- name: message-help
  unicode: f13a
- name: message-text
  unicode: f13b
- name: microphone-mute
  unicode: f13c
- name: microphone
  unicode: f13d
- name: money-withdrawal
  unicode: f13e
- name: motobike
  unicode: f13f
- name: mouse
  unicode: f140
- name: movie-projector
  unicode: f141
- name: movie
  unicode: f142
- name: music-note
  unicode: f143
- name: name-badge
  unicode: f144
- name: network-add
  unicode: f145
- name: network-delete
  unicode: f146
- name: network-remove
  unicode: f147
- name: network
  unicode: f148
- name: newspaper
  unicode: f149
- name: oval
  unicode: f14a
- name: paper-plane
  unicode: f14b
- name: paper-shredders
  unicode: f14c
- name: pattern-lock
  unicode: f14d
- name: pawn
  unicode: f14e
- name: pen
  unicode: f14f
- name: pencil-and-ruller
  unicode: f150
- name: pencil
  unicode: f151
- name: person-add
  unicode: f152
- name: person-checked
  unicode: f153
- name: person-delete
  unicode: f154
- name: person-down
  unicode: f155
- name: person-heart
  unicode: f156
- name: person-list
  unicode: f157
- name: person-message
  unicode: f158
- name: person-next
  unicode: f159
- name: person-previous
  unicode: f15a
- name: person-remove
  unicode: f15b
- name: person-up
  unicode: f15c
- name: person
  unicode: f15d
- name: phone-fax
  unicode: f15e
- name: phone-message
  unicode: f15f
- name: phone
  unicode: f160
- name: piano
  unicode: f161
- name: picture
  unicode: f162
- name: piggy-bank
  unicode: f163
- name: pill-bottle
  unicode: f164
- name: pill
  unicode: f165
- name: pin-location-add
  unicode: f166
- name: pin-location-checked
  unicode: f167
- name: pin-location-delete
  unicode: f168
- name: pin-location-heart
  unicode: f169
- name: pin-location-house
  unicode: f16a
- name: pin-location-remove
  unicode: f16b
- name: pin-location-star
  unicode: f16c
- name: pin-location
  unicode: f16d
- name: pin
  unicode: f16e
- name: pizza-piece
  unicode: f16f
- name: plug
  unicode: f170
- name: pocket-dollar
  unicode: f171
- name: pocket-euro
  unicode: f172
- name: pocket-yen
  unicode: f173
- name: pocket
  unicode: f174
- name: pot
  unicode: f175
- name: printer
  unicode: f176
- name: public
  unicode: f177
- name: puzzle
  unicode: f178
- name: radar-disc
  unicode: f179
- name: radio
  unicode: f17a
- name: radioactive
  unicode: f17b
- name: reload
  unicode: f17c
- name: repeat
  unicode: f17d
- name: reply
  unicode: f17e
- name: ring
  unicode: f17f
- name: road
  unicode: f180
- name: roll
  unicode: f181
- name: rss
  unicode: f182
- name: rugby-ball
  unicode: f183
- name: safety-pin
  unicode: f184
- name: save-box
  unicode: f185
- name: saw
  unicode: f186
- name: science
  unicode: f187
- name: scissor
  unicode: f188
- name: screw-driver
  unicode: f189
- name: scroll-paper
  unicode: f18a
- name: sewing-button
  unicode: f18b
- name: sewing-machine
  unicode: f18c
- name: share
  unicode: f18d
- name: sharing-network
  unicode: f18e
- name: shield-checked
  unicode: f18f
- name: shield-delete
  unicode: f190
- name: shield
  unicode: f191
- name: short
  unicode: f192
- name: shovel
  unicode: f193
- name: sign-board
  unicode: f194
- name: sign-in
  unicode: f195
- name: sign-out
  unicode: f196
- name: sign-road
  unicode: f197
- name: sitemap-1
  unicode: f198
- name: sitemap-2
  unicode: f199
- name: skull
  unicode: f19a
- name: slide-lock
  unicode: f19b
- name: slide-show
  unicode: f19c
- name: space-ship
  unicode: f19d
- name: speaker-decrease
  unicode: f19e
- name: speaker-full
  unicode: f19f
- name: speaker-increase
  unicode: f1a0
- name: speaker-louder
  unicode: f1a1
- name: speaker-low
  unicode: f1a2
- name: speaker-mute
  unicode: f1a3
- name: speaker
  unicode: f1a4
- name: square-dashed
  unicode: f1a5
- name: stack
  unicode: f1a6
- name: stair
  unicode: f1a7
- name: stamp
  unicode: f1a8
- name: star-stick
  unicode: f1a9
- name: stethoscope
  unicode: f1aa
- name: store
  unicode: f1ab
- name: stroller
  unicode: f1ac
- name: suitcase-medical
  unicode: f1ad
- name: suitcase
  unicode: f1ae
- name: syringe
  unicode: f1af
- name: t-shirt
  unicode: f1b0
- name: table-lamp
  unicode: f1b1
- name: tag-percent
  unicode: f1b2
- name: tag-plus-one
  unicode: f1b3
- name: tag-sale
  unicode: f1b4
- name: tag
  unicode: f1b5
- name: tags
  unicode: f1b6
- name: talking
  unicode: f1b7
- name: target
  unicode: f1b8
- name: taxi
  unicode: f1b9
- name: tea-cup
  unicode: f1ba
- name: telephone
  unicode: f1bb
- name: television
  unicode: f1bc
- name: tent
  unicode: f1bd
- name: test-tube
  unicode: f1be
- name: text
  unicode: f1bf
- name: thermometer
  unicode: f1c0
- name: thumb-down
  unicode: f1c1
- name: thumb-up
  unicode: f1c2
- name: ticket
  unicode: f1c3
- name: tie
  unicode: f1c4
- name: tools-box
  unicode: f1c5
- name: traffic-light
  unicode: f1c6
- name: train
  unicode: f1c7
- name: trash
  unicode: f1c8
- name: tree
  unicode: f1c9
- name: trolley-add
  unicode: f1ca
- name: trolley-checked
  unicode: f1cb
- name: trolley-delete
  unicode: f1cc
- name: trolley-down
  unicode: f1cd
- name: trolley-heart
  unicode: f1ce
- name: trolley-next
  unicode: f1cf
- name: trolley-previous
  unicode: f1d0
- name: trolley-remove
  unicode: f1d1
- name: trolley-up
  unicode: f1d2
- name: trolley
  unicode: f1d3
- name: truck
  unicode: f1d4
- name: turn-off
  unicode: f1d5
- name: two-arrow-left-right
  unicode: f1d6
- name: two-arrow-up-down
  unicode: f1d7
- name: umbrella
  unicode: f1d8
- name: unlock
  unicode: f1d9
- name: up-stair
  unicode: f1da
- name: usb
  unicode: f1db
- name: vector-line
  unicode: f1dc
- name: vector
  unicode: f1dd
- name: vespa
  unicode: f1de
- name: vibrate
  unicode: f1df
- name: view-hide
  unicode: f1e0
- name: wallet
  unicode: f1e1
- name: warning-sign
  unicode: f1e2
- name: washing-machine
  unicode: f1e3
- name: watch
  unicode: f1e4
- name: watermelon-piece
  unicode: f1e5
- name: webcam
  unicode: f1e6
- name: website-add
  unicode: f1e7
- name: website-checked
  unicode: f1e8
- name: website-delete
  unicode: f1e9
- name: website-remove
  unicode: f1ea
- name: website
  unicode: f1eb
- name: weight
  unicode: f1ec
- name: wheelbarrow
  unicode: f1ed
- name: wifi
  unicode: f1ee
- name: wine-glass
  unicode: f1ef
- name: yen-money
  unicode: f1f0
- name: zeppelin
  unicode: f1f1
- name: zip
  unicode: f1f2
- name: zoom-in
  unicode: f1f3
- name: zoom-out
  unicode: f1f4
