token: f9f5af68
name: Smarticons Nimble
family: Smarticons Nimble
style: Regular
weight: Regular
version: 1.0.0
filename: SmarticonsNimble.otf
optimized_for: 24px
css_prefix: si-nimble
icon_css_prefix: si-nimble
website: https://smarticons.co/all/set/nimble
premium: true
price: 25.00
download_package: si-nimble.zip
active: false

foundry:
  name: Smarticons
  email: info@smarticons.co
  website: https://smarticons.co

plans:
  - owner

icons:
- name: abulance
  unicode: f000
- name: add
  unicode: f001
- name: adjustment-horizon
  unicode: f002
- name: adjustment-vertical
  unicode: f003
- name: airplane
  unicode: f004
- name: alarm-clock
  unicode: f005
- name: alien
  unicode: f006
- name: anchor
  unicode: f007
- name: arrow-double-down
  unicode: f008
- name: arrow-double-left
  unicode: f009
- name: arrow-double-right
  unicode: f00a
- name: arrow-double-up
  unicode: f00b
- name: arrow-down-up
  unicode: f00c
- name: arrow-down
  unicode: f00d
- name: arrow-forward
  unicode: f00e
- name: arrow-left-right
  unicode: f00f
- name: arrow-next
  unicode: f010
- name: arrow-previous
  unicode: f011
- name: arrow-reply
  unicode: f012
- name: arrow-thick-down
  unicode: f013
- name: arrow-thick-left
  unicode: f014
- name: arrow-thick-right
  unicode: f015
- name: arrow-thick-up
  unicode: f016
- name: arrow-thin-down
  unicode: f017
- name: arrow-thin-left
  unicode: f018
- name: arrow-thin-right
  unicode: f019
- name: arrow-thin-up
  unicode: f01a
- name: arrow-up
  unicode: f01b
- name: asterisk
  unicode: f01c
- name: balloon
  unicode: f01d
- name: baseball-bat
  unicode: f01e
- name: basket-ball
  unicode: f01f
- name: basket
  unicode: f020
- name: beard
  unicode: f021
- name: bell
  unicode: f022
- name: bluetooth
  unicode: f023
- name: bolt
  unicode: f024
- name: book-bookmark
  unicode: f025
- name: book
  unicode: f026
- name: bookmark-add
  unicode: f027
- name: bookmark-remove
  unicode: f028
- name: bookmark
  unicode: f029
- name: bottle
  unicode: f02a
- name: box-download
  unicode: f02b
- name: box-full
  unicode: f02c
- name: box-upload
  unicode: f02d
- name: box
  unicode: f02e
- name: briefcase
  unicode: f02f
- name: brightness
  unicode: f030
- name: bucket
  unicode: f031
- name: building
  unicode: f032
- name: cabinet
  unicode: f033
- name: calculator
  unicode: f034
- name: calendar
  unicode: f035
- name: call-error
  unicode: f036
- name: call-next
  unicode: f037
- name: call-previous
  unicode: f038
- name: call
  unicode: f039
- name: camera
  unicode: f03a
- name: candle
  unicode: f03b
- name: car
  unicode: f03c
- name: cassette
  unicode: f03d
- name: champion
  unicode: f03e
- name: chart-piece
  unicode: f03f
- name: chart
  unicode: f040
- name: checked
  unicode: f041
- name: christmas-ball
  unicode: f042
- name: christmas-tree
  unicode: f043
- name: christmass-hat
  unicode: f044
- name: circle-add
  unicode: f045
- name: circle-arrow-down
  unicode: f046
- name: circle-arrow-left
  unicode: f047
- name: circle-arrow-right
  unicode: f048
- name: circle-arrow-up
  unicode: f049
- name: circle-checked
  unicode: f04a
- name: circle-delete
  unicode: f04b
- name: circle-remove
  unicode: f04c
- name: circle
  unicode: f04d
- name: clip
  unicode: f04e
- name: clipboard
  unicode: f04f
- name: clock
  unicode: f050
- name: cloud-add
  unicode: f051
- name: cloud-delete
  unicode: f052
- name: cloud-download
  unicode: f053
- name: cloud-remove
  unicode: f054
- name: cloud-upload
  unicode: f055
- name: cloud
  unicode: f056
- name: clover
  unicode: f057
- name: column-chart
  unicode: f058
- name: compass
  unicode: f059
- name: computer-share
  unicode: f05a
- name: cone
  unicode: f05b
- name: contrast
  unicode: f05c
- name: copy
  unicode: f05d
- name: cover-cook
  unicode: f05e
- name: crown
  unicode: f05f
- name: cup
  unicode: f060
- name: dashboard
  unicode: f061
- name: database
  unicode: f062
- name: delete
  unicode: f063
- name: depressed
  unicode: f064
- name: diamond
  unicode: f065
- name: disc
  unicode: f066
- name: display
  unicode: f067
- name: document-add
  unicode: f068
- name: document-checked
  unicode: f069
- name: document-delete
  unicode: f06a
- name: document-remove
  unicode: f06b
- name: document-warning
  unicode: f06c
- name: document
  unicode: f06d
- name: door
  unicode: f06e
- name: dot
  unicode: f06f
- name: drop-water
  unicode: f070
- name: egg
  unicode: f071
- name: emoticon-alone
  unicode: f072
- name: emoticon-big-grin
  unicode: f073
- name: emoticon-bored
  unicode: f074
- name: emoticon-confident
  unicode: f075
- name: emoticon-confushed
  unicode: f076
- name: emoticon-crying
  unicode: f077
- name: emoticon-curly-lips
  unicode: f078
- name: emoticon-deep-diving
  unicode: f079
- name: emoticon-depressed
  unicode: f07a
- name: emoticon-determined
  unicode: f07b
- name: emoticon-disappointed
  unicode: f07c
- name: emoticon-friendly
  unicode: f07d
- name: emoticon-frustrated
  unicode: f07e
- name: emoticon-funny
  unicode: f07f
- name: emoticon-grumpy
  unicode: f080
- name: emoticon-halloween
  unicode: f081
- name: emoticon-happy
  unicode: f082
- name: emoticon-horrible
  unicode: f083
- name: emoticon-laughing
  unicode: f084
- name: emoticon-mask
  unicode: f085
- name: emoticon-monks
  unicode: f086
- name: emoticon-mummy
  unicode: f087
- name: emoticon-nerd
  unicode: f088
- name: emoticon-not-talking
  unicode: f089
- name: emoticon-notbad
  unicode: f08a
- name: emoticon-pet
  unicode: f08b
- name: emoticon-pirates
  unicode: f08c
- name: emoticon-sad
  unicode: f08d
- name: emoticon-scared
  unicode: f08e
- name: emoticon-silen
  unicode: f08f
- name: emoticon-smile
  unicode: f090
- name: emoticon-smug
  unicode: f091
- name: emoticon-squint
  unicode: f092
- name: emoticon-straight-face
  unicode: f093
- name: emoticon-surprise
  unicode: f094
- name: emoticon-thinking
  unicode: f095
- name: emoticon-tied
  unicode: f096
- name: emoticon-tongue
  unicode: f097
- name: emoticon-vampire
  unicode: f098
- name: emoticon-waiting
  unicode: f099
- name: emoticon-winking
  unicode: f09a
- name: emoticon-worried
  unicode: f09b
- name: emotion-annoyed
  unicode: f09c
- name: emotion-love
  unicode: f09d
- name: emotion-sleepy
  unicode: f09e
- name: emotion-upset
  unicode: f09f
- name: eyes
  unicode: f0a0
- name: factory
  unicode: f0a1
- name: file-download
  unicode: f0a2
- name: file-upload
  unicode: f0a3
- name: film-35mm
  unicode: f0a4
- name: fire
  unicode: f0a5
- name: first-aid-kit
  unicode: f0a6
- name: flag
  unicode: f0a7
- name: floppy-disk
  unicode: f0a8
- name: flower
  unicode: f0a9
- name: folder-add
  unicode: f0aa
- name: folder-checked
  unicode: f0ab
- name: folder-error
  unicode: f0ac
- name: folder-open
  unicode: f0ad
- name: folder-remove
  unicode: f0ae
- name: folder-share
  unicode: f0af
- name: folder
  unicode: f0b0
- name: four-square
  unicode: f0b1
- name: fridge
  unicode: f0b2
- name: games
  unicode: f0b3
- name: gear
  unicode: f0b4
- name: gift
  unicode: f0b5
- name: glass
  unicode: f0b6
- name: glasses
  unicode: f0b7
- name: global
  unicode: f0b8
- name: hammer
  unicode: f0b9
- name: hat-chef
  unicode: f0ba
- name: head-set
  unicode: f0bb
- name: heart
  unicode: f0bc
- name: history
  unicode: f0bd
- name: house
  unicode: f0be
- name: ice-cream
  unicode: f0bf
- name: info
  unicode: f0c0
- name: ipad
  unicode: f0c1
- name: key
  unicode: f0c2
- name: keyboard
  unicode: f0c3
- name: laptop
  unicode: f0c4
- name: leaf
  unicode: f0c5
- name: light-bulb
  unicode: f0c6
- name: lock
  unicode: f0c7
- name: magnifier
  unicode: f0c8
- name: mail-open
  unicode: f0c9
- name: mail
  unicode: f0ca
- name: map
  unicode: f0cb
- name: mask
  unicode: f0cc
- name: message-dot
  unicode: f0cd
- name: message-text
  unicode: f0ce
- name: message
  unicode: f0cf
- name: microphone-2
  unicode: f0d0
- name: microphone
  unicode: f0d1
- name: mobile
  unicode: f0d2
- name: moon
  unicode: f0d3
- name: mouse
  unicode: f0d4
- name: movie-projector
  unicode: f0d5
- name: music-note
  unicode: f0d6
- name: network
  unicode: f0d7
- name: newspaper
  unicode: f0d8
- name: pacman
  unicode: f0d9
- name: page-end
  unicode: f0da
- name: page-home
  unicode: f0db
- name: paper-plane
  unicode: f0dc
- name: paper-shredders
  unicode: f0dd
- name: pawn
  unicode: f0de
- name: pen
  unicode: f0df
- name: pencil
  unicode: f0e0
- name: person
  unicode: f0e1
- name: phone-dial
  unicode: f0e2
- name: piano
  unicode: f0e3
- name: picture
  unicode: f0e4
- name: piggy-bank
  unicode: f0e5
- name: pill
  unicode: f0e6
- name: pin-location-add
  unicode: f0e7
- name: pin-location-delete
  unicode: f0e8
- name: pin-location-remove
  unicode: f0e9
- name: pin-location
  unicode: f0ea
- name: plugin
  unicode: f0eb
- name: pot
  unicode: f0ec
- name: printer
  unicode: f0ed
- name: puzzle
  unicode: f0ee
- name: radioactive
  unicode: f0ef
- name: remove
  unicode: f0f0
- name: ribbon
  unicode: f0f1
- name: roll
  unicode: f0f2
- name: ruler
  unicode: f0f3
- name: screwdriver
  unicode: f0f4
- name: scube
  unicode: f0f5
- name: shape
  unicode: f0f6
- name: shield-cross
  unicode: f0f7
- name: shield-star
  unicode: f0f8
- name: sign-board-off
  unicode: f0f9
- name: sign-board-on
  unicode: f0fa
- name: sign-board-price
  unicode: f0fb
- name: sign-in
  unicode: f0fc
- name: sign-out
  unicode: f0fd
- name: sign-road
  unicode: f0fe
- name: skull
  unicode: f0ff
- name: slide-show
  unicode: f100
- name: spanner
  unicode: f101
- name: speaker-full
  unicode: f102
- name: speaker-low
  unicode: f103
- name: speaker-mute
  unicode: f104
- name: speaker
  unicode: f105
- name: square-arrow-down
  unicode: f106
- name: square-arrow-left
  unicode: f107
- name: square-arrow-right
  unicode: f108
- name: square-arrow-up
  unicode: f109
- name: square
  unicode: f10a
- name: star
  unicode: f10b
- name: suitcase
  unicode: f10c
- name: tag-plus-one
  unicode: f10d
- name: tag
  unicode: f10e
- name: target
  unicode: f10f
- name: television
  unicode: f110
- name: test-tube
  unicode: f111
- name: thumb-down
  unicode: f112
- name: thumb-up
  unicode: f113
- name: tool-box
  unicode: f114
- name: trash
  unicode: f115
- name: trees
  unicode: f116
- name: triangle-double-left
  unicode: f117
- name: triangle-double-right
  unicode: f118
- name: triangle-down
  unicode: f119
- name: triangle-next
  unicode: f11a
- name: triangle-right
  unicode: f11b
- name: triangle-up
  unicode: f11c
- name: triangle-warning
  unicode: f11d
- name: trolley-add
  unicode: f11e
- name: trolley-error
  unicode: f11f
- name: trolley-next
  unicode: f120
- name: trolley-previous
  unicode: f121
- name: trolley-remove
  unicode: f122
- name: trolley
  unicode: f123
- name: truck
  unicode: f124
- name: umbrella
  unicode: f125
- name: unlock
  unicode: f126
- name: wall
  unicode: f127
- name: wallet
  unicode: f128
- name: wifi
  unicode: f129
- name: zoom-in
  unicode: f12a
- name: zoom-out
  unicode: f12b
