token: fc61fed2
name: Community
family: Community
style: Regular
version: 1.0.0
filename: ss-community.ttf
optimized_for: 32px
css_prefix: ss-community
icon_css_prefix: ss-community
website: https://symbolset.com/icons/community
premium: true
price: 40.00
download_package: ss-community.zip

designer:
  first_name: Wen
  last_name: Ping Huang
  email: wenping527@gmail.com
  website: http://cargocollective.com/wenping

plans:
  - owner

icons:
  - name: 'cursor'
    unicode: 'e001'
  - name: 'crosshair'
    unicode: '2316'
  - name: 'search'
    unicode: '1f50d'
  - name: 'zoomin'
    unicode: 'e002'
  - name: 'zoomout'
    unicode: 'e003'
  - name: 'view'
    unicode: '1f441'
  - name: 'attach'
    unicode: '1f4ce'
  - name: 'link'
    unicode: '1f517'
  - name: 'write'
    unicode: '270e'
  - name: 'writingdisabled'
    unicode: 'e071'
  - name: 'compose'
    unicode: '1f4dd'
  - name: 'lock'
    unicode: '1f512'
  - name: 'unlock'
    unicode: '1f513'
  - name: 'key'
    unicode: '1f511'
  - name: 'ban'
    unicode: '1f6ab'
  - name: 'trash'
    unicode: '1f5d1'
  - name: 'target'
    unicode: '25ce'
  - name: 'lightning'
    unicode: '2607'
  - name: 'tag'
    unicode: '1f3f7'
  - name: 'bookmark'
    unicode: '1f516'
  - name: 'flag'
    unicode: '2691'
  - name: 'like'
    unicode: '1f44d'
  - name: 'dislike'
    unicode: '1f44e'
  - name: 'heart'
    unicode: '2665'
  - name: 'emptyheart'
    unicode: '2661'
  - name: 'star'
    unicode: '22c6'
  - name: 'emptystar'
    unicode: '2606'
  - name: 'trophy'
    unicode: '1f3c6'
  - name: 'award'
    unicode: 'e1c0'
  - name: 'medal'
    unicode: '1f396'
  - name: 'ribbon'
    unicode: '1f380'
  - name: 'shield'
    unicode: 'e012'
  - name: 'sample'
    unicode: 'e200'
  - name: 'crop'
    unicode: 'e201'
  - name: 'compasstool'
    unicode: 'e209'
  - name: 'cut'
    unicode: '2702'
  - name: 'clipboard'
    unicode: '1f4cb'
  - name: 'gridlines'
    unicode: 'e206'
  - name: 'layers'
    unicode: 'e202'
  - name: 'fill'
    unicode: 'e240'
  - name: 'stroke'
    unicode: 'e241'
  - name: 'palette'
    unicode: '1f3a8'
  - name: 'phone'
    unicode: '1f4de'
  - name: 'phonedisabled'
    unicode: 'e300'
  - name: 'megaphone'
    unicode: '1f56b'
  - name: 'rss'
    unicode: 'e310'
  - name: 'podcast'
    unicode: 'e311'
  - name: 'reply'
    unicode: '21a9'
  - name: 'send'
    unicode: '1f585'
  - name: 'mail'
    unicode: '2709'
  - name: 'openmail'
    unicode: 'e356'
  - name: 'inbox'
    unicode: '1f4e5'
  - name: 'chat'
    unicode: '1f4ac'
  - name: 'textchat'
    unicode: 'e396'
  - name: 'user'
    unicode: '1f464'
  - name: 'femaleuser'
    unicode: '1f467'
  - name: 'users'
    unicode: '1f465'
  - name: 'businessuser'
    unicode: 'e407'
  - name: 'parent'
    unicode: 'e442'
  - name: 'baby'
    unicode: '1f476'
  - name: 'hand'
    unicode: 'e410'
  - name: 'foldedhands'
    unicode: '1f64f'
  - name: 'malesign'
    unicode: '2642'
  - name: 'femalesign'
    unicode: '2640'
  - name: 'malefemalesign'
    unicode: '26a5'
  - name: 'malemalesign'
    unicode: '26a3'
  - name: 'femalefemalesign'
    unicode: '26a2'
  - name: 'marriage'
    unicode: '26ad'
  - name: 'cart'
    unicode: 'e500'
  - name: 'gift'
    unicode: '1f381'
  - name: 'banknote'
    unicode: '1f4b5'
  - name: 'coins'
    unicode: 'e543'
  - name: 'piggybank'
    unicode: 'e545'
  - name: 'moneybag'
    unicode: '1f4b0'
  - name: 'calculator'
    unicode: '1f5a9'
  - name: 'equal'
    unicode: '003d'
  - name: 'unequal'
    unicode: '2260'
  - name: 'barchart'
    unicode: '1f4ca'
  - name: 'upwardsbarchart'
    unicode: 'e572'
  - name: 'downwardsbarchart'
    unicode: 'e573'
  - name: 'piechart'
    unicode: 'e570'
  - name: 'analytics'
    unicode: 'e575'
  - name: 'upwardslinechart'
    unicode: '1f4c8'
  - name: 'presentation'
    unicode: 'e57b'
  - name: 'podium'
    unicode: 'e584'
  - name: 'bank'
    unicode: '1f3e6'
  - name: 'scales'
    unicode: '2696'
  - name: 'box'
    unicode: '1f4e6'
  - name: 'home'
    unicode: '2302'
  - name: 'house'
    unicode: '1f3e0'
  - name: 'buildings'
    unicode: '1f3e2'
  - name: 'warehouse'
    unicode: 'e602'
  - name: 'hospital'
    unicode: '26e8'
  - name: 'publicbuilding'
    unicode: '1f3db'
  - name: 'watertower'
    unicode: 'e605'
  - name: 'earth'
    unicode: '1f30e'
  - name: 'globe'
    unicode: '1f310'
  - name: 'navigate'
    unicode: 'e670'
  - name: 'compass'
    unicode: 'e671'
  - name: 'compassnavigate'
    unicode: 'e680'
  - name: 'signpost'
    unicode: 'e672'
  - name: 'map'
    unicode: 'e673'
  - name: 'location'
    unicode: 'e6d0'
  - name: 'pin'
    unicode: '1f4cd'
  - name: 'pushpin'
    unicode: '1f4cc'
  - name: 'hdd'
    unicode: '1f5b4'
  - name: 'music'
    unicode: '266b'
  - name: 'mic'
    unicode: '1f3a4'
  - name: 'headphones'
    unicode: '1f3a7'
  - name: 'volume'
    unicode: '1f508'
  - name: 'lowvolume'
    unicode: '1f509'
  - name: 'highvolume'
    unicode: '1f50a'
  - name: 'disc'
    unicode: '1f4bf'
  - name: 'airplay'
    unicode: 'e800'
  - name: 'camera'
    unicode: '1f4f7'
  - name: 'picture'
    unicode: '1f304'
  - name: 'video'
    unicode: '1f4f9'
  - name: 'playfilm'
    unicode: 'e8b1'
  - name: 'tv'
    unicode: '1f4fa'
  - name: 'play'
    unicode: '25b6'
  - name: 'pause'
    unicode: 'e8a0'
  - name: 'stop'
    unicode: '25a0'
  - name: 'record'
    unicode: '25cf'
  - name: 'rewind'
    unicode: '23ea'
  - name: 'fastforward'
    unicode: '23e9'
  - name: 'skipback'
    unicode: '23ee'
  - name: 'skipforward'
    unicode: '23ed'
  - name: 'eject'
    unicode: '23cf'
  - name: 'repeat'
    unicode: '1f501'
  - name: 'replay'
    unicode: '21ba'
  - name: 'shuffle'
    unicode: '1f500'
  - name: 'page'
    unicode: '1f4c3'
  - name: 'book'
    unicode: '1f4d5'
  - name: 'openbook'
    unicode: '1f4d6'
  - name: 'notebook'
    unicode: '1f4d3'
  - name: 'newspaper'
    unicode: '1f4f0'
  - name: 'grid'
    unicode: 'e9a0'
  - name: 'thumbnails'
    unicode: 'e9a3'
  - name: 'menu'
    unicode: 'ee06'
  - name: 'element'
    unicode: 'e9a4'
  - name: 'filter'
    unicode: 'e9b0'
  - name: 'desktop'
    unicode: '1f4bb'
  - name: 'laptop'
    unicode: 'ea00'
  - name: 'cell'
    unicode: '1f4f1'
  - name: 'battery'
    unicode: '1f50b'
  - name: 'highbattery'
    unicode: 'ea10'
  - name: 'mediumbattery'
    unicode: 'ea11'
  - name: 'lowbattery'
    unicode: 'ea12'
  - name: 'emptybattery'
    unicode: 'ea13'
  - name: 'chargingbattery'
    unicode: 'ea14'
  - name: 'microchip'
    unicode: 'e7c0'
  - name: 'network'
    unicode: '1f5a7'
  - name: 'lightbulb'
    unicode: '1f4a1'
  - name: 'campfire'
    unicode: '1f525'
  - name: 'frame'
    unicode: '1f5bc'
  - name: 'pipe'
    unicode: 'ea8f'
  - name: 'atom'
    unicode: '269b'
  - name: 'download'
    unicode: 'eb01'
  - name: 'downloadcloud'
    unicode: 'eb00'
  - name: 'upload'
    unicode: 'eb41'
  - name: 'uploadcloud'
    unicode: 'eb40'
  - name: 'fork'
    unicode: 'eb80'
  - name: 'merge'
    unicode: 'eb81'
  - name: 'transfer'
    unicode: '21c6'
  - name: 'refresh'
    unicode: '21bb'
  - name: 'sync'
    unicode: '1f5d8'
  - name: 'loading'
    unicode: 'eb83'
  - name: 'wifi'
    unicode: 'eb84'
  - name: 'connection'
    unicode: 'eb85'
  - name: 'file'
    unicode: '1f4c4'
  - name: 'folder'
    unicode: '1f4c1'
  - name: 'quote'
    unicode: '201c'
  - name: 'text'
    unicode: 'ed00'
  - name: 'font'
    unicode: 'ed01'
  - name: 'print'
    unicode: '2399'
  - name: 'fax'
    unicode: '1f4e0'
  - name: 'list'
    unicode: 'ed50'
  - name: 'layout'
    unicode: 'eda0'
  - name: 'action'
    unicode: 'ee00'
  - name: 'redirect'
    unicode: '21aa'
  - name: 'expand'
    unicode: '2922'
  - name: 'contract'
    unicode: 'ee01'
  - name: 'scaleup'
    unicode: 'ee04'
  - name: 'scaledown'
    unicode: 'ee05'
  - name: 'power'
    unicode: 'ee10'
  - name: 'help'
    unicode: '2753'
  - name: 'info'
    unicode: '2139'
  - name: 'alert'
    unicode: '26a0'
  - name: 'caution'
    unicode: '26d4'
  - name: 'plus'
    unicode: '002b'
  - name: 'hyphen'
    unicode: '002d'
  - name: 'check'
    unicode: '2713'
  - name: 'delete'
    unicode: '2421'
  - name: 'tree'
    unicode: '1f333'
  - name: 'evergreen'
    unicode: '1f332'
  - name: 'leaf'
    unicode: '1f342'
  - name: 'seedling'
    unicode: '1f331'
  - name: 'settings'
    unicode: '2699'
  - name: 'dashboard'
    unicode: 'f000'
  - name: 'notifications'
    unicode: '1f514'
  - name: 'reminderribbon'
    unicode: '1f397'
  - name: 'wrench'
    unicode: '1f527'
  - name: 'hammer'
    unicode: '1f528'
  - name: 'screwdriver'
    unicode: 'f037'
  - name: 'shovel'
    unicode: 'f03a'
  - name: 'pitchfork'
    unicode: 'f03b'
  - name: 'hourglass'
    unicode: '23f3'
  - name: 'clock'
    unicode: '23f2'
  - name: 'stopwatch'
    unicode: '23f1'
  - name: 'alarmclock'
    unicode: '23f0'
  - name: 'calendar'
    unicode: '1f4c5'
  - name: 'addcalendar'
    unicode: 'f070'
  - name: 'removecalendar'
    unicode: 'f071'
  - name: 'checkcalendar'
    unicode: 'f072'
  - name: 'deletecalendar'
    unicode: 'f073'
  - name: 'cheese'
    unicode: 'f101'
  - name: 'sausage'
    unicode: 'f103'
  - name: 'burger'
    unicode: '1f354'
  - name: 'sidedish'
    unicode: '1f35a'
  - name: 'bread'
    unicode: '1f35e'
  - name: 'mug'
    unicode: '2615'
  - name: 'coffee'
    unicode: 'f120'
  - name: 'beer'
    unicode: '1f37a'
  - name: 'bottle'
    unicode: 'f122'
  - name: 'wineglass'
    unicode: '1f377'
  - name: 'soda'
    unicode: 'f124'
  - name: 'cup'
    unicode: 'f125'
  - name: 'drinkingwater'
    unicode: '1f6b0'
  - name: 'utensils'
    unicode: '1f374'
  - name: 'platter'
    unicode: 'f166'
  - name: 'plate'
    unicode: 'f169'
  - name: 'graduationcap'
    unicode: '1f393'
  - name: 'handbag'
    unicode: '1f45c'
  - name: 'briefcase'
    unicode: '1f4bc'
  - name: 'suitcase'
    unicode: 'f420'
  - name: 'hanger'
    unicode: 'f1a0'
  - name: 'thermometer'
    unicode: '1f321'
  - name: 'cloud'
    unicode: '2601'
  - name: 'clouds'
    unicode: 'f220'
  - name: 'sun'
    unicode: '2600'
  - name: 'partlycloudy'
    unicode: '26c5'
  - name: 'rain'
    unicode: '1f327'
  - name: 'thunderstorm'
    unicode: '26c8'
  - name: 'snow'
    unicode: '1f328'
  - name: 'umbrella'
    unicode: '2602'
  - name: 'wind'
    unicode: 'f212'
  - name: 'tornado'
    unicode: '1f32a'
  - name: 'snowflake'
    unicode: '2744'
  - name: 'crescentmoon'
    unicode: '1f319'
  - name: 'plug'
    unicode: '1f50c'
  - name: 'car'
    unicode: '1f698'
  - name: 'taxi'
    unicode: '1f696'
  - name: 'policecar'
    unicode: '1f694'
  - name: 'train'
    unicode: '1f686'
  - name: 'bus'
    unicode: '1f68d'
  - name: 'truck'
    unicode: '1f69a'
  - name: 'tractor'
    unicode: '1f69c'
  - name: 'plane'
    unicode: '2708'
  - name: 'bike'
    unicode: '1f6b2'
  - name: 'scooter'
    unicode: 'f306'
  - name: 'boat'
    unicode: '1f6a2'
  - name: 'rocket'
    unicode: '1f680'
  - name: 'fuel'
    unicode: '26fd'
  - name: 'firehydrant'
    unicode: 'f317'
  - name: 'wheelchair'
    unicode: '267f'
  - name: 'dumbbell'
    unicode: 'f416'
  - name: 'medicine'
    unicode: 'f4ba'
  - name: 'medicalbag'
    unicode: 'f4b1'
  - name: 'stethoscope'
    unicode: 'f4b4'
  - name: 'microscope'
    unicode: '1f52c'
  - name: 'syringe'
    unicode: '1f489'
  - name: 'pill'
    unicode: '1f48a'
  - name: 'pillbottle'
    unicode: 'f4b5'
  - name: 'mortarandpestle'
    unicode: 'f4b9'
  - name: 'flask'
    unicode: 'f4c0'
  - name: 'brain'
    unicode: 'f4d3'
  - name: 'blood'
    unicode: 'f4d2'
  - name: 'dna'
    unicode: 'f4c2'
  - name: 'beatingheart'
    unicode: '1f493'
  - name: 'up'
    unicode: '2b06'
  - name: 'upright'
    unicode: '2b08'
  - name: 'right'
    unicode: '27a1'
  - name: 'downright'
    unicode: '2b0a'
  - name: 'down'
    unicode: '2b07'
  - name: 'downleft'
    unicode: '2b0b'
  - name: 'left'
    unicode: '2b05'
  - name: 'upleft'
    unicode: '2b09'
  - name: 'navigateup'
    unicode: 'f500'
  - name: 'navigateright'
    unicode: '25bb'
  - name: 'navigatedown'
    unicode: 'f501'
  - name: 'navigateleft'
    unicode: '25c5'
  - name: 'directup'
    unicode: '25b4'
  - name: 'directright'
    unicode: '25b9'
  - name: 'dropdown'
    unicode: '25be'
  - name: 'directleft'
    unicode: '25c3'
  - name: 'retweet'
    unicode: 'f600'

