token: 64b4a382
name: Elements
family: Elements
style: Regular
version: 1.0.0
filename: 'ss-elements.ttf'
optimized_for: 36px
css_prefix: ss-elements
icon_css_prefix: ss-elements
website: https://symbolset.com/icons/elements
premium: true
price: 10.00
download_package: ss-elements.zip

designer:
  first_name: Jory
  last_name: Raphael
  email: jory@sensibleworld.com
  website: http://sensibleworld.com

plans:
  - owner

icons:
  - name: 'sun'
    unicode: '2600'
  - name: 'crescentmoon'
    unicode: '1f319'
  - name: 'cloud'
    unicode: '2601'
  - name: 'clouds'
    unicode: 'f220'
  - name: 'partlycloudy'
    unicode: '26c5'
  - name: 'cloudynight'
    unicode: 'f221'
  - name: 'mostlycloudyday'
    unicode: '1f325'
  - name: 'mostlycloudynight'
    unicode: 'f223'
  - name: 'rainbow'
    unicode: '1f308'
  - name: 'shootingstar'
    unicode: '1f320'
  - name: 'rain'
    unicode: '1f327'
  - name: 'heavyrain'
    unicode: '26c6'
  - name: 'rainyday'
    unicode: '1f326'
  - name: 'rainynight'
    unicode: 'f226'
  - name: 'freezingrain'
    unicode: 'f227'
  - name: 'heavyfreezingrain'
    unicode: 'f228'
  - name: 'freezingrainday'
    unicode: 'f229'
  - name: 'freezingrainnight'
    unicode: 'f22a'
  - name: 'snow'
    unicode: '1f328'
  - name: 'heavysnow'
    unicode: 'f232'
  - name: 'snowday'
    unicode: 'f233'
  - name: 'snownight'
    unicode: 'f234'
  - name: 'rainsnow'
    unicode: 'f235'
  - name: 'heavyrainsnow'
    unicode: 'f236'
  - name: 'rainsnowday'
    unicode: 'f237'
  - name: 'rainsnownight'
    unicode: 'f238'
  - name: 'sleet'
    unicode: 'f23b'
  - name: 'heavysleet'
    unicode: 'f23c'
  - name: 'sleetday'
    unicode: 'f23d'
  - name: 'sleetnight'
    unicode: 'f23e'
  - name: 'droplet'
    unicode: '1f4a7'
  - name: 'droplets'
    unicode: 'f22b'
  - name: 'pellet'
    unicode: 'f239'
  - name: 'pellets'
    unicode: 'f23a'
  - name: 'snowflake'
    unicode: '2744'
  - name: 'snowflakes'
    unicode: 'f241'
  - name: 'snowflakedrops'
    unicode: 'f242'
  - name: 'snowflakepellets'
    unicode: 'f243'
  - name: 'star'
    unicode: '22c6'
  - name: 'stars'
    unicode: 'e1b0'
  - name: 'hail'
    unicode: 'f244'
  - name: 'heavyhail'
    unicode: 'f245'
  - name: 'hailday'
    unicode: 'f246'
  - name: 'hailnight'
    unicode: 'f247'
  - name: 'thunderstorm'
    unicode: '26c8'
  - name: 'thunderstormday'
    unicode: 'f249'
  - name: 'thunderstormnight'
    unicode: 'f24a'
  - name: 'lightning'
    unicode: '2607'
  - name: 'lightningbolts'
    unicode: 'f24e'
  - name: 'wind'
    unicode: 'f212'
  - name: 'windrain'
    unicode: 'f24b'
  - name: 'windsnow'
    unicode: 'f24c'
  - name: 'windpellets'
    unicode: 'f24d'
  - name: 'dust'
    unicode: 'f248'
  - name: 'haze'
    unicode: 'f250'
  - name: 'hazeday'
    unicode: 'f251'
  - name: 'hazenight'
    unicode: 'f252'
  - name: 'fog'
    unicode: '1f32b'
  - name: 'fogday'
    unicode: 'f253'
  - name: 'fognight'
    unicode: 'f254'
  - name: 'fullthermometer'
    unicode: 'f205'
  - name: 'highthermometer'
    unicode: 'f206'
  - name: 'thermometer'
    unicode: '1f321'
  - name: 'lowthermometer'
    unicode: 'f208'
  - name: 'emptythermometer'
    unicode: 'f209'
  - name: 'thermometersnowflake'
    unicode: 'f20c'
  - name: 'thermometerday'
    unicode: 'f20a'
  - name: 'emptythermometerday'
    unicode: 'f20b'
  - name: 'sunset'
    unicode: '1f307'
  - name: 'sunrise'
    unicode: '1f305'
  - name: 'newmoon'
    unicode: '1f311'
  - name: 'waxingcrescentmoon'
    unicode: '1f312'
  - name: 'firstquartermoon'
    unicode: '1f313'
  - name: 'waxinggibbousmoon'
    unicode: '1f314'
  - name: 'fullmoon'
    unicode: '1f315'
  - name: 'waninggibbousmoon'
    unicode: '1f316'
  - name: 'lastquartermoon'
    unicode: '1f317'
  - name: 'waningcrescentmoon'
    unicode: '1f318'
  - name: 'hurricane'
    unicode: '1f300'
  - name: 'tornado'
    unicode: '1f32a'
  - name: 'compass'
    unicode: 'e671'
  - name: 'northeast'
    unicode: 'f531'
  - name: 'east'
    unicode: 'f532'
  - name: 'southeast'
    unicode: 'f533'
  - name: 'south'
    unicode: 'f534'
  - name: 'southwest'
    unicode: 'f535'
  - name: 'west'
    unicode: 'f536'
  - name: 'northwest'
    unicode: 'f537'
  - name: 'smoke'
    unicode: 'f255'
  - name: 'umbrella'
    unicode: '2602'
  - name: 'skylift'
    unicode: '1f6a1'
  - name: 'doublelift'
    unicode: 'f381'
  - name: 'triplelift'
    unicode: 'f382'
  - name: 'quadlift'
    unicode: 'f383'
  - name: 'mountains'
    unicode: '26f0'
  - name: 'alert'
    unicode: '26a0'
  - name: 'easy'
    unicode: 'f390'
  - name: 'intermediate'
    unicode: 'f391'
  - name: 'difficult'
    unicode: 'f392'
  - name: 'expert'
    unicode: 'f393'
