token: a68843a8
name: Geomicons Squared
family: Geomicons Squared
style: Regular
version: 1.0.0
filename: ss-geomicons-squared.ttf
optimized_for: 32px
css_prefix: ss-geomicons-squared
icon_css_prefix: ss-geomicons-squared
website: https://symbolset.com/icons/geomicons-squared
premium: true
price: 40.00
download_package: ss-geomicons-squared.zip

designer:
  first_name: Brent
  last_name: Jackson
  email: jxnblk@gmail.com
  website: http://jxnblk.com

plans:
  - owner

icons:
  - name: 'crosshair'
    unicode: '2316'
  - name: 'search'
    unicode: '1f50e'
  - name: 'view'
    unicode: '1f440'
  - name: 'link'
    unicode: '1f517'
  - name: 'move'
    unicode: 'e070'
  - name: 'write'
    unicode: '270e'
  - name: 'compose'
    unicode: '1f4dd'
  - name: 'lock'
    unicode: '1f512'
  - name: 'unlock'
    unicode: '1f513'
  - name: 'key'
    unicode: '1f511'
  - name: 'backspace'
    unicode: '232b'
  - name: 'ban'
    unicode: '1f6ab'
  - name: 'trash'
    unicode: 'e0d0'
  - name: 'radioactive'
    unicode: '2622'
  - name: 'skull'
    unicode: '1f480'
  - name: 'lightning'
    unicode: '2607'
  - name: 'tag'
    unicode: 'e100'
  - name: 'bookmark'
    unicode: '1f516'
  - name: 'flag'
    unicode: '2691'
  - name: 'like'
    unicode: '1f44d'
  - name: 'dislike'
    unicode: '1f44e'
  - name: 'heart'
    unicode: '2665'
  - name: 'star'
    unicode: '22c6'
  - name: 'shield'
    unicode: 'e012'
  - name: 'trophy'
    unicode: '1f3c6'
  - name: 'medal'
    unicode: 'e1c1'
  - name: 'crown'
    unicode: '1f451'
  - name: 'bullseye'
    unicode: '1f3af'
  - name: 'crop'
    unicode: 'e201'
  - name: 'layers'
    unicode: 'e202'
  - name: 'cut'
    unicode: '2702'
  - name: 'clipboard'
    unicode: '1f4cb'
  - name: 'brush'
    unicode: 'e224'
  - name: 'paintroller'
    unicode: 'e225'
  - name: 'paint'
    unicode: 'e229'
  - name: 'phone'
    unicode: '1f4de'
  - name: 'rotaryphone'
    unicode: '260e'
  - name: 'voicemail'
    unicode: '2315'
  - name: 'megaphone'
    unicode: '1f4e2'
  - name: 'rss'
    unicode: 'e310'
  - name: 'reply'
    unicode: '21a9'
  - name: 'envelope'
    unicode: '2709'
  - name: 'inbox'
    unicode: '1f4e5'
  - name: 'chat'
    unicode: '1f4ac'
  - name: 'user'
    unicode: '1f464'
  - name: 'users'
    unicode: '1f465'
  - name: 'usergroup'
    unicode: 'e400'
  - name: 'male'
    unicode: 'e450'
  - name: 'userprofile'
    unicode: 'e406'
  - name: 'contacts'
    unicode: '1f4c7'
  - name: 'ghost'
    unicode: '1f47b'
  - name: 'cart'
    unicode: 'e500'
  - name: 'emptycart'
    unicode: 'e507'
  - name: 'gift'
    unicode: '1f381'
  - name: 'calculator'
    unicode: 'e551'
  - name: 'barchart'
    unicode: '1f4ca'
  - name: 'piechart'
    unicode: 'e570'
  - name: 'stock'
    unicode: 'e579'
  - name: 'box'
    unicode: '1f4e6'
  - name: 'home'
    unicode: '2302'
  - name: 'warehouse'
    unicode: 'e602'
  - name: 'globe'
    unicode: '1f310'
  - name: 'navigate'
    unicode: 'e670'
  - name: 'compass'
    unicode: 'e671'
  - name: 'signpost'
    unicode: 'e672'
  - name: 'map'
    unicode: 'e673'
  - name: 'location'
    unicode: 'e6d0'
  - name: 'pin'
    unicode: '1f4cd'
  - name: 'code'
    unicode: 'e780'
  - name: 'bug'
    unicode: '1f41b'
  - name: 'puzzle'
    unicode: 'e710'
  - name: 'airplay'
    unicode: 'e800'
  - name: 'music'
    unicode: '266b'
  - name: 'mic'
    unicode: '1f3a4'
  - name: 'headphones'
    unicode: '1f3a7'
  - name: 'volume'
    unicode: '1f508'
  - name: 'metronome'
    unicode: 'e807'
  - name: 'camera'
    unicode: '1f4f7'
  - name: 'picture'
    unicode: '1f304'
  - name: 'video'
    unicode: '1f4f9'
  - name: 'tv'
    unicode: '1f4fa'
  - name: 'videogame'
    unicode: '1f3ae'
  - name: 'dpad'
    unicode: 'ea44'
  - name: 'play'
    unicode: '25b6'
  - name: 'pause'
    unicode: 'e8a0'
  - name: 'stop'
    unicode: '25a0'
  - name: 'record'
    unicode: '25cf'
  - name: 'rewind'
    unicode: '23ea'
  - name: 'fastforward'
    unicode: '23e9'
  - name: 'skipback'
    unicode: '23ee'
  - name: 'skipforward'
    unicode: '23ed'
  - name: 'eject'
    unicode: '23cf'
  - name: 'repeat'
    unicode: '1f501'
  - name: 'shuffle'
    unicode: '1f500'
  - name: 'storagebox'
    unicode: 'e901'
  - name: 'book'
    unicode: '1f4d5'
  - name: 'notebook'
    unicode: '1f4d3'
  - name: 'grid'
    unicode: 'e9a0'
  - name: 'rows'
    unicode: 'e9a1'
  - name: 'columns'
    unicode: 'e9a2'
  - name: 'thumbnails'
    unicode: 'e9a3'
  - name: 'filter'
    unicode: 'e9b0'
  - name: 'desktop'
    unicode: '1f4bb'
  - name: 'laptop'
    unicode: 'ea00'
  - name: 'tablet'
    unicode: 'ea01'
  - name: 'smartphone'
    unicode: 'ea02'
  - name: 'cell'
    unicode: '1f4f1'
  - name: 'battery'
    unicode: '1f50b'
  - name: 'highbattery'
    unicode: 'ea10'
  - name: 'mediumbattery'
    unicode: 'ea11'
  - name: 'lowbattery'
    unicode: 'ea12'
  - name: 'emptybattery'
    unicode: 'ea13'
  - name: 'chargingbattery'
    unicode: 'ea14'
  - name: 'lightbulb'
    unicode: '1f4a1'
  - name: 'spade'
    unicode: '2660'
  - name: 'club'
    unicode: '2663'
  - name: 'diamond'
    unicode: '2666'
  - name: 'download'
    unicode: 'eb01'
  - name: 'downloadbox'
    unicode: 'eb02'
  - name: 'upload'
    unicode: 'eb41'
  - name: 'uploadcloud'
    unicode: 'eb40'
  - name: 'addcloud'
    unicode: 'eb90'
  - name: 'removecloud'
    unicode: 'eb91'
  - name: 'fork'
    unicode: 'eb80'
  - name: 'merge'
    unicode: 'eb81'
  - name: 'replay'
    unicode: '21ba'
  - name: 'refresh'
    unicode: '21bb'
  - name: 'sync'
    unicode: 'eb82'
  - name: 'wifi'
    unicode: 'eb84'
  - name: 'index'
    unicode: 'e902'
  - name: 'file'
    unicode: '1f4c4'
  - name: 'files'
    unicode: 'ec00'
  - name: 'folder'
    unicode: '1f4c1'
  - name: 'print'
    unicode: '2399'
  - name: 'list'
    unicode: 'ed50'
  - name: 'layout'
    unicode: 'eda0'
  - name: 'action'
    unicode: 'ee00'
  - name: 'redirect'
    unicode: '21aa'
  - name: 'expand'
    unicode: '2922'
  - name: 'contract'
    unicode: 'ee01'
  - name: 'scaleup'
    unicode: 'ee04'
  - name: 'scaledown'
    unicode: 'ee05'
  - name: 'info'
    unicode: '2139'
  - name: 'alert'
    unicode: '26a0'
  - name: 'plus'
    unicode: '002b'
  - name: 'hyphen'
    unicode: '002d'
  - name: 'check'
    unicode: '2713'
  - name: 'delete'
    unicode: '2421'
  - name: 'cat'
    unicode: '1f408'
  - name: 'bird'
    unicode: '1f426'
  - name: 'owl'
    unicode: 'ef01'
  - name: 'bone'
    unicode: 'ef60'
  - name: 'poo'
    unicode: '1f4a9'
  - name: 'tree'
    unicode: '1f332'
  - name: 'leaf'
    unicode: '1f342'
  - name: 'flower'
    unicode: '2698'
  - name: 'mountains'
    unicode: '26f0'
  - name: 'settings'
    unicode: '2699'
  - name: 'dashboard'
    unicode: 'f000'
  - name: 'notifications'
    unicode: '1f514'
  - name: 'contrast'
    unicode: '25d0'
  - name: 'magnet'
    unicode: 'f012'
  - name: 'toolbox'
    unicode: 'f030'
  - name: 'wrench'
    unicode: '1f527'
  - name: 'hammer'
    unicode: '1f528'
  - name: 'screwdriver'
    unicode: 'f037'
  - name: 'nut'
    unicode: '1f529'
  - name: 'clock'
    unicode: '23f2'
  - name: 'stopwatch'
    unicode: '23f1'
  - name: 'watch'
    unicode: '231a'
  - name: 'alarmclock'
    unicode: '23f0'
  - name: 'counterclockwise'
    unicode: '2940'
  - name: 'clockwise'
    unicode: '2941'
  - name: 'calendar'
    unicode: '1f4c5'
  - name: 'addcalendar'
    unicode: 'f070'
  - name: 'removecalendar'
    unicode: 'f071'
  - name: 'checkcalendar'
    unicode: 'f072'
  - name: 'icecream'
    unicode: '1f368'
  - name: 'popsicle'
    unicode: 'f119'
  - name: 'coffee'
    unicode: 'f120'
  - name: 'espresso'
    unicode: 'eff0'
  - name: 'mug'
    unicode: '2615'
  - name: 'tea'
    unicode: '1f375'
  - name: 'beer'
    unicode: '1f37a'
  - name: 'wineglass'
    unicode: '1f377'
  - name: 'soda'
    unicode: 'f124'
  - name: 'utensils'
    unicode: '1f374'
  - name: 'tshirt'
    unicode: '1f455'
  - name: 'tie'
    unicode: 'f1a2'
  - name: 'glasses'
    unicode: '1f453'
  - name: 'thermometer'
    unicode: 'f201'
  - name: 'sun'
    unicode: '2600'
  - name: 'cloud'
    unicode: '2601'
  - name: 'crescentmoon'
    unicode: '1f319'
  - name: 'planet'
    unicode: 'f2a0'
  - name: 'fan'
    unicode: 'f280'
  - name: 'outlet'
    unicode: 'f282'
  - name: 'car'
    unicode: '1f698'
  - name: 'plane'
    unicode: '2708'
  - name: 'bike'
    unicode: '1f6b2'
  - name: 'sailboat'
    unicode: '26f5'
  - name: 'rocket'
    unicode: '1f680'
  - name: 'highway'
    unicode: 'f320'
  - name: 'briefcase'
    unicode: '1f4bc'
  - name: 'medicalbag'
    unicode: 'f4b1'
  - name: 'flask'
    unicode: 'f4c0'
  - name: 'burst'
    unicode: 'f552'
  - name: 'infinity'
    unicode: '221e'
  - name: 'up'
    unicode: '2b06'
  - name: 'right'
    unicode: '27a1'
  - name: 'down'
    unicode: '2b07'
  - name: 'left'
    unicode: '2b05'
  - name: 'navigateup'
    unicode: 'f500'
  - name: 'navigateright'
    unicode: '25bb'
  - name: 'navigatedown'
    unicode: 'f501'
  - name: 'navigateleft'
    unicode: '25c5'
  - name: 'directup'
    unicode: '25b4'
  - name: 'directright'
    unicode: '25b9'
  - name: 'dropdown'
    unicode: '25be'
  - name: 'directleft'
    unicode: '25c3'
  - name: 'share'
    unicode: 'f601'
  - name: 'retweet'
    unicode: 'f600'
  - name: 'facebook'
    unicode: 'f610'
  - name: 'twitter'
    unicode: 'f611'
  - name: 'android'
    unicode: 'f6f3'

