token: d8c07ea3
name: Glyphish Outlined
family: Glyphish Outlined
style: Regular
version: 1.0.0
filename: ss-glyphish-outlined.ttf
optimized_for: 28px
css_prefix: ss-glyphish-outlined
icon_css_prefix: ss-glyphish-outlined
website: https://symbolset.com/icons/glyphish
premium: true
price: 25.00
download_package: ss-glyphish-outlined.zip
active: false

foundry:
  name: Glyphish
  email: info@glyphish.com
  website: http://www.glyphish.com

plans:
  - owner

icons:
  - name: 'cursor'
    unicode: 'e001'
  - name: 'crosshair'
    unicode: '2316'
  - name: 'search'
    unicode: '1f50e'
  - name: 'zoomin'
    unicode: 'e002'
  - name: 'zoomout'
    unicode: 'e003'
  - name: 'view'
    unicode: '1f441'
  - name: 'binoculars'
    unicode: 'e010'
  - name: 'incognito'
    unicode: 'e015'
  - name: 'radar'
    unicode: 'e014'
  - name: 'attach'
    unicode: '1f4ce'
  - name: 'link'
    unicode: '1f517'
  - name: 'write'
    unicode: '270e'
  - name: 'compose'
    unicode: '1f4dd'
  - name: 'lock'
    unicode: '1f512'
  - name: 'unlock'
    unicode: '1f513'
  - name: 'combinationlock'
    unicode: 'e072'
  - name: 'key'
    unicode: '1f511'
  - name: 'keyhole'
    unicode: 'e073'
  - name: 'vip'
    unicode: 'e074'
  - name: 'trash'
    unicode: '1f5d1'
  - name: 'target'
    unicode: '25ce'
  - name: 'bullseye'
    unicode: '1f3af'
  - name: 'lightning'
    unicode: '2607'
  - name: 'radioactive'
    unicode: '2622'
  - name: 'skull'
    unicode: '1f480'
  - name: 'skullandcrossbones'
    unicode: '2620'
  - name: 'tag'
    unicode: '1f3f7'
  - name: 'tags'
    unicode: 'e104'
  - name: 'pricetag'
    unicode: 'e102'
  - name: 'flag'
    unicode: '2691'
  - name: 'like'
    unicode: '1f44d'
  - name: 'dislike'
    unicode: '1f44e'
  - name: 'heart'
    unicode: '2665'
  - name: 'star'
    unicode: '22c6'
  - name: 'archive'
    unicode: '1f5c3'
  - name: 'badge'
    unicode: '1f4db'
  - name: 'trophy'
    unicode: '1f3c6'
  - name: 'medal'
    unicode: '1f396'
  - name: 'crown'
    unicode: '1f451'
  - name: 'layers'
    unicode: 'e202'
  - name: 'layergroup'
    unicode: 'e207'
  - name: 'cut'
    unicode: '2702'
  - name: 'magicwand'
    unicode: 'e203'
  - name: 'clipboard'
    unicode: '1f4cb'
  - name: 'ruler'
    unicode: '1f4cf'
  - name: 'brush'
    unicode: 'e224'
  - name: 'paintroller'
    unicode: 'e225'
  - name: 'rubberstamp'
    unicode: 'e226'
  - name: 'palette'
    unicode: '1f3a8'
  - name: 'phone'
    unicode: '1f4de'
  - name: 'voicemail'
    unicode: '2315'
  - name: 'megaphone'
    unicode: '1f4e2'
  - name: 'at'
    unicode: '0040'
  - name: 'reply'
    unicode: '21a9'
  - name: 'replyall'
    unicode: 'e355'
  - name: 'mailbox'
    unicode: '1f4eb'
  - name: 'send'
    unicode: '1f585'
  - name: 'mail'
    unicode: '2709'
  - name: 'inbox'
    unicode: '1f4e5'
  - name: 'stamp'
    unicode: 'e351'
  - name: 'chat'
    unicode: '1f4ac'
  - name: 'chats'
    unicode: '1f5ea'
  - name: 'ellipsischat'
    unicode: 'e399'
  - name: 'ellipsis'
    unicode: '2026'
  - name: 'smile'
    unicode: '263b'
  - name: 'user'
    unicode: '1f464'
  - name: 'femaleuser'
    unicode: '1f467'
  - name: 'users'
    unicode: '1f465'
  - name: 'baby'
    unicode: '1f476'
  - name: 'alien'
    unicode: '1f47d'
  - name: 'ghost'
    unicode: '1f47b'
  - name: 'footsteps'
    unicode: '1f463'
  - name: 'usergroup'
    unicode: 'e400'
  - name: 'contacts'
    unicode: '1f4c7'
  - name: 'userprofile'
    unicode: 'e406'
  - name: 'cart'
    unicode: 'e500'
  - name: 'shoppingbag'
    unicode: '1f6cd'
  - name: 'gift'
    unicode: '1f381'
  - name: 'store'
    unicode: '1f3ea'
  - name: 'barcode'
    unicode: 'e532'
  - name: 'creditcard'
    unicode: '1f4b3'
  - name: 'creditcards'
    unicode: 'e548'
  - name: 'banknote'
    unicode: '1f4b5'
  - name: 'currency'
    unicode: '1f4b1'
  - name: 'piggybank'
    unicode: 'e545'
  - name: 'calculator'
    unicode: '1f5a9'
  - name: 'tally'
    unicode: 'e553'
  - name: 'bank'
    unicode: '1f3e6'
  - name: 'scales'
    unicode: '2696'
  - name: 'gavel'
    unicode: 'e583'
  - name: 'meeting'
    unicode: 'e581'
  - name: 'presentation'
    unicode: 'e57b'
  - name: 'piechart'
    unicode: 'e570'
  - name: 'barchart'
    unicode: '1f4ca'
  - name: 'activity'
    unicode: 'e57a'
  - name: 'flowchart'
    unicode: 'e577'
  - name: 'stock'
    unicode: '1f5e0'
  - name: 'box'
    unicode: '1f4e6'
  - name: 'crate'
    unicode: 'e5d8'
  - name: 'handtruck'
    unicode: 'e5e9'
  - name: 'home'
    unicode: '2302'
  - name: 'fence'
    unicode: 'e601'
  - name: 'buildings'
    unicode: '1f3e2'
  - name: 'hotel'
    unicode: '1f3e8'
  - name: 'warehouse'
    unicode: 'e602'
  - name: 'castle'
    unicode: '1f3f0'
  - name: 'globe'
    unicode: '1f310'
  - name: 'earth'
    unicode: '1f30e'
  - name: 'navigate'
    unicode: 'e670'
  - name: 'compassnavigate'
    unicode: 'e680'
  - name: 'compass'
    unicode: 'e671'
  - name: 'signpost'
    unicode: 'e672'
  - name: 'map'
    unicode: 'e673'
  - name: 'location'
    unicode: 'e6d0'
  - name: 'pin'
    unicode: '1f4cd'
  - name: 'pushpin'
    unicode: '1f4cc'
  - name: 'maplocation'
    unicode: 'e6d1'
  - name: 'floppydisk'
    unicode: '1f4be'
  - name: 'puzzle'
    unicode: 'e710'
  - name: 'install'
    unicode: 'e711'
  - name: 'window'
    unicode: '1f5d4'
  - name: 'windows'
    unicode: '1f5d7'
  - name: 'commandline'
    unicode: 'e781'
  - name: 'bug'
    unicode: '1f41b'
  - name: 'database'
    unicode: 'e7a0'
  - name: 'music'
    unicode: '266b'
  - name: 'eighthnote'
    unicode: '266a'
  - name: 'guitar'
    unicode: '1f3b8'
  - name: 'piano'
    unicode: '1f3b9'
  - name: 'pianokeys'
    unicode: 'e80a'
  - name: 'trumpet'
    unicode: '1f3ba'
  - name: 'mic'
    unicode: '1f3a4'
  - name: 'studiomic'
    unicode: '1f399'
  - name: 'headphones'
    unicode: '1f3a7'
  - name: 'mutevolume'
    unicode: 'e808'
  - name: 'volume'
    unicode: '1f508'
  - name: 'lowvolume'
    unicode: '1f509'
  - name: 'highvolume'
    unicode: '1f50a'
  - name: 'ipod'
    unicode: 'ea06'
  - name: 'stereo'
    unicode: 'e801'
  - name: 'speaker'
    unicode: 'e809'
  - name: 'vinylrecord'
    unicode: 'e810'
  - name: 'disc'
    unicode: '1f4bf'
  - name: 'playlist'
    unicode: 'e820'
  - name: 'airplay'
    unicode: 'e800'
  - name: 'camera'
    unicode: '1f4f7'
  - name: 'picture'
    unicode: '1f304'
  - name: 'pictures'
    unicode: 'e851'
  - name: 'video'
    unicode: '1f4f9'
  - name: 'film'
    unicode: '1f39e'
  - name: 'filmroll'
    unicode: 'e8b2'
  - name: 'widescreenfilm'
    unicode: 'e8b4'
  - name: 'clapboard'
    unicode: '1f3ac'
  - name: 'tv'
    unicode: '1f4fa'
  - name: 'flatscreen'
    unicode: 'e8c0'
  - name: 'videogame'
    unicode: '1f3ae'
  - name: 'repeat'
    unicode: '1f501'
  - name: 'replay'
    unicode: '21ba'
  - name: 'shuffle'
    unicode: '1f500'
  - name: 'filecabinet'
    unicode: '1f5c4'
  - name: 'storagebox'
    unicode: 'e901'
  - name: 'index'
    unicode: '1f5c2'
  - name: 'page'
    unicode: '1f4c3'
  - name: 'book'
    unicode: '1f4d5'
  - name: 'openbook'
    unicode: '1f4d6'
  - name: 'notebook'
    unicode: '1f4d3'
  - name: 'spiralbound'
    unicode: '1f5d2'
  - name: 'newspaper'
    unicode: '1f4f0'
  - name: 'notepad'
    unicode: 'e972'
  - name: 'cards'
    unicode: 'e904'
  - name: 'notice'
    unicode: 'e973'
  - name: 'grid'
    unicode: 'e9a0'
  - name: 'rows'
    unicode: 'e9a1'
  - name: 'menu'
    unicode: 'ee06'
  - name: 'filter'
    unicode: 'e9b0'
  - name: 'ascending'
    unicode: 'e9b2'
  - name: 'descending'
    unicode: 'e9b3'
  - name: 'desktop'
    unicode: '1f4bb'
  - name: 'laptop'
    unicode: 'ea00'
  - name: 'tablet'
    unicode: 'ea01'
  - name: 'smartphone'
    unicode: 'ea02'
  - name: 'cell'
    unicode: '1f4f1'
  - name: 'battery'
    unicode: '1f50b'
  - name: 'door'
    unicode: '1f6aa'
  - name: 'washer'
    unicode: 'ea80'
  - name: 'birdhouse'
    unicode: 'eab4'
  - name: 'doghouse'
    unicode: 'eab5'
  - name: 'lightbulb'
    unicode: '1f4a1'
  - name: 'lamp'
    unicode: 'ea8a'
  - name: 'spraycan'
    unicode: 'ea8c'
  - name: 'spraybottle'
    unicode: 'ea8d'
  - name: 'chair'
    unicode: 'ea8b'
  - name: 'frame'
    unicode: '1f5bc'
  - name: 'flowerframe'
    unicode: 'ea93'
  - name: 'atom'
    unicode: '269b'
  - name: 'telescope'
    unicode: '1f52d'
  - name: 'balloon'
    unicode: '1f388'
  - name: 'fuzzydice'
    unicode: 'ea87'
  - name: 'magiclamp'
    unicode: 'ea8e'
  - name: 'slingshot'
    unicode: 'eaa5'
  - name: 'bomb'
    unicode: '1f4a3'
  - name: 'gun'
    unicode: '1f52b'
  - name: 'sword'
    unicode: 'eaa6'
  - name: 'swords'
    unicode: '2694'
  - name: 'bowandarrow'
    unicode: 'eaa7'
  - name: 'targetdummy'
    unicode: 'eaa8'
  - name: 'downloadcloud'
    unicode: 'eb00'
  - name: 'download'
    unicode: 'eb01'
  - name: 'downloadbox'
    unicode: 'eb02'
  - name: 'uploadcloud'
    unicode: 'eb40'
  - name: 'upload'
    unicode: 'eb41'
  - name: 'merge'
    unicode: 'eb81'
  - name: 'fork'
    unicode: 'eb80'
  - name: 'joinpath'
    unicode: 'eb88'
  - name: 'splitpath'
    unicode: 'eb89'
  - name: 'forkpath'
    unicode: 'eb8a'
  - name: 'refresh'
    unicode: '21bb'
  - name: 'sync'
    unicode: '1f5d8'
  - name: 'wifi'
    unicode: 'eb84'
  - name: 'connection'
    unicode: 'eb85'
  - name: 'file'
    unicode: '1f4c4'
  - name: 'files'
    unicode: 'ec00'
  - name: 'folder'
    unicode: '1f4c1'
  - name: 'anchor'
    unicode: '2693'
  - name: 'print'
    unicode: '2399'
  - name: 'list'
    unicode: 'ed50'
  - name: 'starlist'
    unicode: 'ed51'
  - name: 'layout'
    unicode: 'eda0'
  - name: 'twoup'
    unicode: 'eda1'
  - name: 'threeup'
    unicode: 'eda2'
  - name: 'fourup'
    unicode: 'eda3'
  - name: 'action'
    unicode: 'ee00'
  - name: 'expand'
    unicode: '2922'
  - name: 'contract'
    unicode: 'ee01'
  - name: 'lifepreserver'
    unicode: 'ee11'
  - name: 'help'
    unicode: '2753'
  - name: 'info'
    unicode: '2139'
  - name: 'alert'
    unicode: '26a0'
  - name: 'plus'
    unicode: '002b'
  - name: 'hyphen'
    unicode: '002d'
  - name: 'check'
    unicode: '2713'
  - name: 'fish'
    unicode: '1f41f'
  - name: 'whale'
    unicode: '1f40b'
  - name: 'bird'
    unicode: '1f426'
  - name: 'pawprint'
    unicode: 'ef62'
  - name: 'bone'
    unicode: 'ef60'
  - name: 'tree'
    unicode: '1f332'
  - name: 'flower'
    unicode: '2698'
  - name: 'gem'
    unicode: '1f48e'
  - name: 'mountains'
    unicode: '26f0'
  - name: 'settings'
    unicode: '2699'
  - name: 'dashboard'
    unicode: 'f000'
  - name: 'dial'
    unicode: 'f004'
  - name: 'notifications'
    unicode: '1f514'
  - name: 'toggles'
    unicode: '1f39a'
  - name: 'switch'
    unicode: 'f002'
  - name: 'brightness'
    unicode: '1f506'
  - name: 'contrast'
    unicode: '25d0'
  - name: 'flash'
    unicode: '2301'
  - name: 'magnet'
    unicode: 'f012'
  - name: 'level'
    unicode: 'f038'
  - name: 'toolbox'
    unicode: 'f030'
  - name: 'hammer'
    unicode: '1f528'
  - name: 'wrench'
    unicode: '1f527'
  - name: 'nut'
    unicode: '1f529'
  - name: 'screw'
    unicode: 'f039'
  - name: 'clock'
    unicode: '23f2'
  - name: 'stopwatch'
    unicode: '23f1'
  - name: 'alarmclock'
    unicode: '23f0'
  - name: 'counterclockwise'
    unicode: '2940'
  - name: 'calendar'
    unicode: '1f4c5'
  - name: 'food'
    unicode: 'f180'
  - name: 'egg'
    unicode: 'f100'
  - name: 'chickenleg'
    unicode: '1f357'
  - name: 'pizza'
    unicode: '1f355'
  - name: 'birthdaycake'
    unicode: '1f382'
  - name: 'icecream'
    unicode: '1f368'
  - name: 'popsicle'
    unicode: 'f119'
  - name: 'coffee'
    unicode: 'f120'
  - name: 'mug'
    unicode: '2615'
  - name: 'beer'
    unicode: '1f37a'
  - name: 'bottle'
    unicode: 'f122'
  - name: 'wineglass'
    unicode: '1f377'
  - name: 'wine'
    unicode: 'f123'
  - name: 'cocktail'
    unicode: '1f378'
  - name: 'cup'
    unicode: 'f125'
  - name: 'waterbottle'
    unicode: 'f128'
  - name: 'utensils'
    unicode: '1f374'
  - name: 'measuringcup'
    unicode: 'f162'
  - name: 'helmet'
    unicode: 'f1b2'
  - name: 'graduationcap'
    unicode: '1f393'
  - name: 'glasses'
    unicode: '1f453'
  - name: 'sunglasses'
    unicode: '1f576'
  - name: 'tie'
    unicode: 'f1a2'
  - name: 'bowtie'
    unicode: 'f1a3'
  - name: 'tshirt'
    unicode: '1f455'
  - name: 'jersey'
    unicode: 'f1c0'
  - name: 'sock'
    unicode: 'f1b4'
  - name: 'handbag'
    unicode: '1f45c'
  - name: 'briefcase'
    unicode: '1f4bc'
  - name: 'messengerbag'
    unicode: 'f1a5'
  - name: 'hanger'
    unicode: 'f1a0'
  - name: 'safetypin'
    unicode: 'f1fa'
  - name: 'thermometer'
    unicode: 'f201'
  - name: 'cloud'
    unicode: '2601'
  - name: 'sun'
    unicode: '2600'
  - name: 'partlycloudy'
    unicode: '26c5'
  - name: 'rain'
    unicode: '1f327'
  - name: 'thunderstorm'
    unicode: '26c8'
  - name: 'snow'
    unicode: '1f328'
  - name: 'umbrella'
    unicode: '2602'
  - name: 'crescentmoon'
    unicode: '1f319'
  - name: 'planet'
    unicode: 'f2a0'
  - name: 'recycle'
    unicode: '2672'
  - name: 'outlet'
    unicode: 'f282'
  - name: 'car'
    unicode: '1f698'
  - name: 'train'
    unicode: '1f686'
  - name: 'bus'
    unicode: '1f68d'
  - name: 'trailer'
    unicode: 'f301'
  - name: 'plane'
    unicode: '2708'
  - name: 'boat'
    unicode: '1f6a2'
  - name: 'sailboat'
    unicode: '26f5'
  - name: 'boat'
    unicode: '1f6a2'
  - name: 'schooner'
    unicode: 'f305'
  - name: 'rocket'
    unicode: '1f680'
  - name: 'satellite'
    unicode: '1f6f0'
  - name: 'ufo'
    unicode: 'f304'
  - name: 'helm'
    unicode: '2388'
  - name: 'fuel'
    unicode: '26fd'
  - name: 'firehydrant'
    unicode: 'f317'
  - name: 'theatre'
    unicode: '1f3ad'
  - name: 'ticket'
    unicode: '1f3ab'
  - name: 'golf'
    unicode: '26f3'
  - name: 'golfshot'
    unicode: 'f40b'
  - name: 'basketball'
    unicode: '1f3c0'
  - name: 'hockeymask'
    unicode: 'f40c'
  - name: 'billiards'
    unicode: '1f3b1'
  - name: 'baseball'
    unicode: '26be'
  - name: 'baseballfield'
    unicode: 'f40d'
  - name: 'tennis'
    unicode: '1f3be'
  - name: 'tabletennis'
    unicode: 'f402'
  - name: 'boxing'
    unicode: 'f405'
  - name: 'bowling'
    unicode: 'f406'
  - name: 'football'
    unicode: '1f3c8'
  - name: 'soccer'
    unicode: '26bd'
  - name: 'dumbbell'
    unicode: 'f416'
  - name: 'fishhook'
    unicode: 'f40e'
  - name: 'gameplan'
    unicode: 'f40f'
  - name: 'hiker'
    unicode: 'f410'
  - name: 'runner'
    unicode: '1f3c3'
  - name: 'pedestrian'
    unicode: '1f6b6'
  - name: 'callbell'
    unicode: '1f6ce'
  - name: 'shower'
    unicode: '1f6bf'
  - name: 'bandage'
    unicode: 'f4b2'
  - name: 'pill'
    unicode: '1f48a'
  - name: 'flask'
    unicode: 'f4c0'
  - name: 'testtube'
    unicode: 'f4c1'
  - name: 'pulse'
    unicode: 'f4b8'
  - name: 'up'
    unicode: '2b06'
  - name: 'right'
    unicode: '27a1'
  - name: 'down'
    unicode: '2b07'
  - name: 'left'
    unicode: '2b05'
  - name: 'rightward'
    unicode: 'f503'
  - name: 'leftward'
    unicode: 'f505'
  - name: 'squiggle'
    unicode: '21dd'
  - name: 'retweet'
    unicode: 'f600'
