token: d551138a
name: Gizmo
family: Gizmo
style: Regular
version: 1.0.0
filename: ss-gizmo.ttf
optimized_for: 64px
css_prefix: ss-gizmo
icon_css_prefix: ss-gizmo
website: https://symbolset.com/icons/gizmo
premium: true
price: 50.00
download_package: ss-gizmo.zip
active: false

foundry:
  name: Dutch Icons
  email: info@dutchicon.com
  website: http://www.dutchicon.com

plans:
  - owner

icons:
  - name: 'cursor'
    unicode: 'e001'
  - name: 'crosshair'
    unicode: '2316'
  - name: 'search'
    unicode: '1f50e'
  - name: 'zoomin'
    unicode: 'e002'
  - name: 'zoomout'
    unicode: 'e003'
  - name: 'view'
    unicode: '1f440'
  - name: 'attach'
    unicode: '1f4ce'
  - name: 'link'
    unicode: '1f517'
  - name: 'unlink'
    unicode: 'e011'
  - name: 'move'
    unicode: 'e070'
  - name: 'write'
    unicode: '270e'
  - name: 'writingdisabled'
    unicode: 'e071'
  - name: 'erase'
    unicode: '2710'
  - name: 'compose'
    unicode: '1f4dd'
  - name: 'lock'
    unicode: '1f512'
  - name: 'unlock'
    unicode: '1f513'
  - name: 'key'
    unicode: '1f511'
  - name: 'backspace'
    unicode: '232b'
  - name: 'ban'
    unicode: '1f6ab'
  - name: 'smoking'
    unicode: '1f6ac'
  - name: 'nosmoking'
    unicode: '1f6ad'
  - name: 'trash'
    unicode: 'e0d0'
  - name: 'target'
    unicode: '25ce'
  - name: 'tag'
    unicode: 'e100'
  - name: 'bookmark'
    unicode: '1f516'
  - name: 'flag'
    unicode: '2691'
  - name: 'like'
    unicode: '1f44d'
  - name: 'dislike'
    unicode: '1f44e'
  - name: 'heart'
    unicode: '2665'
  - name: 'star'
    unicode: '22c6'
  - name: 'sample'
    unicode: 'e200'
  - name: 'crop'
    unicode: 'e201'
  - name: 'layers'
    unicode: 'e202'
  - name: 'layergroup'
    unicode: 'e207'
  - name: 'pen'
    unicode: '2712'
  - name: 'bezier'
    unicode: 'e2a0'
  - name: 'pixels'
    unicode: 'e2a1'
  - name: 'phone'
    unicode: '1f4de'
  - name: 'phonedisabled'
    unicode: 'e300'
  - name: 'touchtonephone'
    unicode: '260f'
  - name: 'mail'
    unicode: '2709'
  - name: 'inbox'
    unicode: '1f4e5'
  - name: 'outbox'
    unicode: '1f4e4'
  - name: 'chat'
    unicode: '1f4ac'
  - name: 'user'
    unicode: '1f464'
  - name: 'users'
    unicode: '1f465'
  - name: 'usergroup'
    unicode: 'e400'
  - name: 'businessuser'
    unicode: 'e407'
  - name: 'man'
    unicode: '1f468'
  - name: 'male'
    unicode: 'e450'
  - name: 'woman'
    unicode: '1f469'
  - name: 'female'
    unicode: 'e451'
  - name: 'raisedhand'
    unicode: '270b'
  - name: 'hand'
    unicode: 'e410'
  - name: 'pointup'
    unicode: '1f446'
  - name: 'pointupright'
    unicode: 'f510'
  - name: 'pointright'
    unicode: '1f449'
  - name: 'pointdownright'
    unicode: 'f511'
  - name: 'pointdown'
    unicode: '1f447'
  - name: 'pointdownleft'
    unicode: 'f512'
  - name: 'pointleft'
    unicode: '1f448'
  - name: 'pointupleft'
    unicode: 'f513'
  - name: 'cart'
    unicode: 'e500'
  - name: 'creditcard'
    unicode: '1f4b3'
  - name: 'calculator'
    unicode: 'e551'
  - name: 'barchart'
    unicode: '1f4ca'
  - name: 'piechart'
    unicode: 'e570'
  - name: 'box'
    unicode: '1f4e6'
  - name: 'home'
    unicode: '2302'
  - name: 'globe'
    unicode: '1f30e'
  - name: 'navigate'
    unicode: 'e670'
  - name: 'compass'
    unicode: 'e671'
  - name: 'signpost'
    unicode: 'e672'
  - name: 'location'
    unicode: 'e6d0'
  - name: 'floppydisk'
    unicode: '1f4be'
  - name: 'database'
    unicode: 'e7a0'
  - name: 'hdd'
    unicode: 'e7b0'
  - name: 'microchip'
    unicode: 'e7c0'
  - name: 'music'
    unicode: '266b'
  - name: 'headphones'
    unicode: '1f3a7'
  - name: 'discdrive'
    unicode: 'ea42'
  - name: 'volume'
    unicode: '1f508'
  - name: 'lowvolume'
    unicode: '1f509'
  - name: 'mediumvolume'
    unicode: 'e803'
  - name: 'highvolume'
    unicode: '1f50a'
  - name: 'airplay'
    unicode: 'e800'
  - name: 'camera'
    unicode: '1f4f7'
  - name: 'picture'
    unicode: '1f304'
  - name: 'video'
    unicode: '1f4f9'
  - name: 'webcam'
    unicode: 'ea41'
  - name: 'film'
    unicode: 'e8b0'
  - name: 'playvideo'
    unicode: 'e8a1'
  - name: 'videogame'
    unicode: '1f3ae'
  - name: 'play'
    unicode: '25b6'
  - name: 'pause'
    unicode: 'e8a0'
  - name: 'stop'
    unicode: '25a0'
  - name: 'record'
    unicode: '25cf'
  - name: 'rewind'
    unicode: '23ea'
  - name: 'fastforward'
    unicode: '23e9'
  - name: 'skipback'
    unicode: '23ee'
  - name: 'skipforward'
    unicode: '23ed'
  - name: 'eject'
    unicode: '23cf'
  - name: 'repeat'
    unicode: '1f501'
  - name: 'replay'
    unicode: '21ba'
  - name: 'shuffle'
    unicode: '1f500'
  - name: 'index'
    unicode: 'e902'
  - name: 'storagebox'
    unicode: 'e901'
  - name: 'book'
    unicode: '1f4d5'
  - name: 'notebook'
    unicode: '1f4d3'
  - name: 'newspaper'
    unicode: '1f4f0'
  - name: 'gridlines'
    unicode: 'e206'
  - name: 'rows'
    unicode: 'e9a1'
  - name: 'columns'
    unicode: 'e9a2'
  - name: 'thumbnails'
    unicode: 'e9a3'
  - name: 'mouse'
    unicode: 'ea40'
  - name: 'usb'
    unicode: 'eb86'
  - name: 'desktop'
    unicode: '1f4bb'
  - name: 'laptop'
    unicode: 'ea00'
  - name: 'tablet'
    unicode: 'ea01'
  - name: 'smartphone'
    unicode: 'ea02'
  - name: 'cell'
    unicode: '1f4f1'
  - name: 'battery'
    unicode: '1f50b'
  - name: 'highbattery'
    unicode: 'ea10'
  - name: 'mediumbattery'
    unicode: 'ea11'
  - name: 'lowbattery'
    unicode: 'ea12'
  - name: 'chargingbattery'
    unicode: 'ea14'
  - name: 'lightbulb'
    unicode: '1f4a1'
  - name: 'washer'
    unicode: 'ea80'
  - name: 'downloadcloud'
    unicode: 'eb00'
  - name: 'download'
    unicode: 'eb01'
  - name: 'downloadbox'
    unicode: 'eb02'
  - name: 'uploadcloud'
    unicode: 'eb40'
  - name: 'upload'
    unicode: 'eb41'
  - name: 'uploadbox'
    unicode: 'eb42'
  - name: 'fork'
    unicode: 'eb80'
  - name: 'merge'
    unicode: 'eb81'
  - name: 'refresh'
    unicode: '21bb'
  - name: 'sync'
    unicode: 'eb82'
  - name: 'loading'
    unicode: 'eb83'
  - name: 'file'
    unicode: '1f4c4'
  - name: 'files'
    unicode: 'ec00'
  - name: 'addfile'
    unicode: 'ec01'
  - name: 'removefile'
    unicode: 'ec02'
  - name: 'checkfile'
    unicode: 'ec03'
  - name: 'deletefile'
    unicode: 'ec04'
  - name: 'exe'
    unicode: 'ec30'
  - name: 'zip'
    unicode: 'ec31'
  - name: 'doc'
    unicode: 'ec32'
  - name: 'pdf'
    unicode: 'ec34'
  - name: 'jpg'
    unicode: 'ec35'
  - name: 'png'
    unicode: 'ec36'
  - name: 'mp3'
    unicode: 'ec37'
  - name: 'rar'
    unicode: 'ec38'
  - name: 'gif'
    unicode: 'ec39'
  - name: 'folder'
    unicode: '1f4c1'
  - name: 'openfolder'
    unicode: '1f4c2'
  - name: 'downloadfolder'
    unicode: 'ec76'
  - name: 'uploadfolder'
    unicode: 'ec77'
  - name: 'quote'
    unicode: '201c'
  - name: 'unquote'
    unicode: '201d'
  - name: 'print'
    unicode: '2399'
  - name: 'copier'
    unicode: 'ed42'
  - name: 'fax'
    unicode: '1f4e0'
  - name: 'scanner'
    unicode: 'ed43'
  - name: 'printregistration'
    unicode: 'ed44'
  - name: 'shredder'
    unicode: 'ed40'
  - name: 'expand'
    unicode: '2922'
  - name: 'contract'
    unicode: 'ee01'
  - name: 'help'
    unicode: '2753'
  - name: 'info'
    unicode: '2139'
  - name: 'alert'
    unicode: '26a0'
  - name: 'caution'
    unicode: '26d4'
  - name: 'logout'
    unicode: 'ee02'
  - name: 'login'
    unicode: 'ee03'
  - name: 'scaleup'
    unicode: 'ee04'
  - name: 'scaledown'
    unicode: 'ee05'
  - name: 'plus'
    unicode: '002b'
  - name: 'hyphen'
    unicode: '002d'
  - name: 'check'
    unicode: '2713'
  - name: 'delete'
    unicode: '2421'
  - name: 'notifications'
    unicode: '1f514'
  - name: 'notificationsdisabled'
    unicode: '1f515'
  - name: 'clock'
    unicode: '23f2'
  - name: 'stopwatch'
    unicode: '23f1'
  - name: 'alarmclock'
    unicode: '23f0'
  - name: 'egg'
    unicode: 'f100'
  - name: 'eggs'
    unicode: 'f107'
  - name: 'cheese'
    unicode: 'f101'
  - name: 'chickenleg'
    unicode: '1f357'
  - name: 'pizzapie'
    unicode: 'efe0'
  - name: 'pizza'
    unicode: '1f355'
  - name: 'cheesepizza'
    unicode: 'efe1'
  - name: 'frenchfries'
    unicode: '1f35f'
  - name: 'apple'
    unicode: '1f34f'
  - name: 'carrot'
    unicode: 'f111'
  - name: 'broccoli'
    unicode: 'f117'
  - name: 'cucumber'
    unicode: 'f116'
  - name: 'orange'
    unicode: '1f34a'
  - name: 'lemon'
    unicode: '1f34b'
  - name: 'onion'
    unicode: 'f115'
  - name: 'bellpepper'
    unicode: 'f114'
  - name: 'peas'
    unicode: 'f112'
  - name: 'grapes'
    unicode: '1f347'
  - name: 'strawberry'
    unicode: '1f353'
  - name: 'bread'
    unicode: '1f35e'
  - name: 'mug'
    unicode: '2615'
  - name: 'mugs'
    unicode: 'f12b'
  - name: 'espresso'
    unicode: 'eff0'
  - name: 'macchiato'
    unicode: 'eff1'
  - name: 'cappucino'
    unicode: 'eff2'
  - name: 'latte'
    unicode: 'eff3'
  - name: 'icedcoffee'
    unicode: 'eff4'
  - name: 'coffeebean'
    unicode: 'eff5'
  - name: 'coffeemilk'
    unicode: 'eff6'
  - name: 'coffeefoam'
    unicode: 'eff7'
  - name: 'coffeesugar'
    unicode: 'eff8'
  - name: 'sugarpackets'
    unicode: 'f135'
  - name: 'capsule'
    unicode: 'eff9'
  - name: 'capsulerecycling'
    unicode: 'effa'
  - name: 'insertcapsule'
    unicode: 'effb'
  - name: 'tea'
    unicode: '1f375'
  - name: 'teabag'
    unicode: 'effc'
  - name: 'jug'
    unicode: 'f126'
  - name: 'pitcher'
    unicode: 'f19b'
  - name: 'kettle'
    unicode: 'f19c'
  - name: 'wineglass'
    unicode: '1f377'
  - name: 'sugar'
    unicode: 'f134'
  - name: 'oven'
    unicode: 'f140'
  - name: 'stove'
    unicode: 'f141'
  - name: 'vent'
    unicode: 'f143'
  - name: 'exhaust'
    unicode: 'f144'
  - name: 'steam'
    unicode: '2668'
  - name: 'dishwasher'
    unicode: 'f192'
  - name: 'toaster'
    unicode: 'f193'
  - name: 'microwave'
    unicode: 'f194'
  - name: 'electrickettle'
    unicode: 'f195'
  - name: 'refrigerator'
    unicode: 'f196'
  - name: 'freezer'
    unicode: 'f197'
  - name: 'utensils'
    unicode: '1f374'
  - name: 'cookingutensils'
    unicode: 'f151'
  - name: 'whisk'
    unicode: 'f152'
  - name: 'pizzacutter'
    unicode: 'f153'
  - name: 'measuringcup'
    unicode: 'f162'
  - name: 'colander'
    unicode: 'f163'
  - name: 'eggtimer'
    unicode: 'f165'
  - name: 'platter'
    unicode: 'f166'
  - name: 'plates'
    unicode: 'f167'
  - name: 'steamplate'
    unicode: 'f198'
  - name: 'cups'
    unicode: 'f12a'
  - name: 'steamglass'
    unicode: 'f199'
  - name: 'pot'
    unicode: 'f168'
  - name: 'steampot'
    unicode: 'f19a'
  - name: 'chef'
    unicode: 'f172'
  - name: 'weathervane'
    unicode: 'f200'
  - name: 'thermometer'
    unicode: 'f201'
  - name: 'thermometerup'
    unicode: 'f203'
  - name: 'thermometerdown'
    unicode: 'f204'
  - name: 'droplet'
    unicode: '1f4a7'
  - name: 'sunrise'
    unicode: '1f305'
  - name: 'sunset'
    unicode: '1f307'
  - name: 'sun'
    unicode: '2600'
  - name: 'cloud'
    unicode: '2601'
  - name: 'clouds'
    unicode: 'f220'
  - name: 'partlycloudy'
    unicode: '26c5'
  - name: 'rain'
    unicode: '2614'
  - name: 'rainheavy'
    unicode: 'f224'
  - name: 'lightning'
    unicode: '2607'
  - name: 'thunderstorm'
    unicode: '26c8'
  - name: 'umbrella'
    unicode: '2602'
  - name: 'rainumbrella'
    unicode: 'f270'
  - name: 'rainbow'
    unicode: '1f308'
  - name: 'rainbowclouds'
    unicode: 'f214'
  - name: 'fog'
    unicode: 'f211'
  - name: 'wind'
    unicode: 'f212'
  - name: 'tornado'
    unicode: 'f213'
  - name: 'snowflake'
    unicode: '2744'
  - name: 'snowcrystal'
    unicode: '2746'
  - name: 'lightsnow'
    unicode: 'f230'
  - name: 'snow'
    unicode: 'f231'
  - name: 'heavysnow'
    unicode: 'f232'
  - name: 'hail'
    unicode: 'f244'
  - name: 'crescentmoon'
    unicode: '1f319'
  - name: 'waxingcrescentmoon'
    unicode: '1f312'
  - name: 'firstquartermoon'
    unicode: '1f313'
  - name: 'waxinggibbousmoon'
    unicode: '1f314'
  - name: 'waninggibbousmoon'
    unicode: '1f316'
  - name: 'lastquartermoon'
    unicode: '1f317'
  - name: 'waningcrescentmoon'
    unicode: '1f318'
  - name: 'fan'
    unicode: 'f280'
  - name: 'bike'
    unicode: '1f6b2'
  - name: 'wheelchair'
    unicode: '267f'
  - name: 'briefcase'
    unicode: '1f4bc'
  - name: 'hanger'
    unicode: 'f1a0'
  - name: 'comb'
    unicode: 'f1a1'
  - name: 'medicalcross'
    unicode: 'f4b0'
  - name: 'up'
    unicode: '2b06'
  - name: 'upright'
    unicode: '2b08'
  - name: 'right'
    unicode: '27a1'
  - name: 'downright'
    unicode: '2b0a'
  - name: 'down'
    unicode: '2b07'
  - name: 'downleft'
    unicode: '2b0b'
  - name: 'left'
    unicode: '2b05'
  - name: 'upleft'
    unicode: '2b09'
  - name: 'navigateup'
    unicode: 'f500'
  - name: 'navigateright'
    unicode: '25bb'
  - name: 'navigatedown'
    unicode: 'f501'
  - name: 'navigateleft'
    unicode: '25c5'
  - name: 'retweet'
    unicode: 'f600'
  - name: 'share'
    unicode: 'f601'
