token: 3b52907d
name: Junior
family: Junior
style: Regular
version: 1.0.0
filename: ss-junior.ttf
optimized_for: 16px
css_prefix: ss-junior
icon_css_prefix: ss-junior
website: https://symbolset.com/icons/junior
premium: true
price: 40.00
download_package: ss-junior.zip

designer:
  first_name: Jory
  last_name: Raphael
  email: jory@sensibleworld.com
  website: http://sensibleworld.com

plans:
  - owner

icons:
  - name: 'cursor'
    unicode: 'e001'
  - name: 'crosshair'
    unicode: '2316'
  - name: 'search'
    unicode: '1f50e'
  - name: 'zoomin'
    unicode: 'e002'
  - name: 'zoomout'
    unicode: 'e003'
  - name: 'view'
    unicode: '1f440'
  - name: 'viewdisabled'
    unicode: 'e013'
  - name: 'binoculars'
    unicode: 'e010'
  - name: 'attach'
    unicode: '1f4ce'
  - name: 'link'
    unicode: '1f517'
  - name: 'move'
    unicode: 'e070'
  - name: 'write'
    unicode: '270e'
  - name: 'writingdisabled'
    unicode: 'e071'
  - name: 'compose'
    unicode: '1f4dd'
  - name: 'lock'
    unicode: '1f512'
  - name: 'unlock'
    unicode: '1f513'
  - name: 'key'
    unicode: '1f511'
  - name: 'backspace'
    unicode: '232b'
  - name: 'ban'
    unicode: '1f6ab'
  - name: 'trash'
    unicode: 'e0d0'
  - name: 'target'
    unicode: '25ce'
  - name: 'skull'
    unicode: '1f480'
  - name: 'tag'
    unicode: 'e100'
  - name: 'bookmark'
    unicode: '1f516'
  - name: 'flag'
    unicode: '2691'
  - name: 'like'
    unicode: '1f44d'
  - name: 'dislike'
    unicode: '1f44e'
  - name: 'heart'
    unicode: '2665'
  - name: 'unheart'
    unicode: 'e1aa'
  - name: 'star'
    unicode: '22c6'
  - name: 'unstar'
    unicode: 'e1ab'
  - name: 'sample'
    unicode: 'e200'
  - name: 'crop'
    unicode: 'e201'
  - name: 'cut'
    unicode: '2702'
  - name: 'clipboard'
    unicode: '1f4cb'
  - name: 'ruler'
    unicode: 'e208'
  - name: 'gridlines'
    unicode: 'e206'
  - name: 'pencilbrushpen'
    unicode: 'e223'
  - name: 'paintroller'
    unicode: 'e225'
  - name: 'paint'
    unicode: 'e229'
  - name: 'paintdisabled'
    unicode: 'e22a'
  - name: 'paintedit'
    unicode: 'e22b'
  - name: 'pixels'
    unicode: 'e2a1'
  - name: 'phone'
    unicode: '1f4de'
  - name: 'phonedisabled'
    unicode: 'e300'
  - name: 'addressbook'
    unicode: '1f4d1'
  - name: 'voicemail'
    unicode: '2315'
  - name: 'mailbox'
    unicode: '1f4eb'
  - name: 'send'
    unicode: 'e350'
  - name: 'paperairplane'
    unicode: 'e353'
  - name: 'mail'
    unicode: '2709'
  - name: 'inbox'
    unicode: '1f4e5'
  - name: 'inboxes'
    unicode: 'e354'
  - name: 'outbox'
    unicode: '1f4e4'
  - name: 'chat'
    unicode: '1f4ac'
  - name: 'textchat'
    unicode: 'e396'
  - name: 'ellipsischat'
    unicode: 'e399'
  - name: 'ellipsis'
    unicode: '2026'
  - name: 'smile'
    unicode: '263b'
  - name: 'frown'
    unicode: '2639'
  - name: 'surprise'
    unicode: '1f62e'
  - name: 'user'
    unicode: '1f464'
  - name: 'femaleuser'
    unicode: '1f467'
  - name: 'users'
    unicode: '1f465'
  - name: 'robot'
    unicode: 'e440'
  - name: 'ghost'
    unicode: '1f47b'
  - name: 'contacts'
    unicode: '1f4c7'
  - name: 'pointup'
    unicode: '1f446'
  - name: 'pointright'
    unicode: '1f449'
  - name: 'pointdown'
    unicode: '1f447'
  - name: 'pointleft'
    unicode: '1f448'
  - name: 'cart'
    unicode: 'e500'
  - name: 'shoppingbag'
    unicode: 'e520'
  - name: 'store'
    unicode: '1f3ea'
  - name: 'creditcard'
    unicode: '1f4b3'
  - name: 'banknote'
    unicode: '1f4b5'
  - name: 'calculator'
    unicode: 'e551'
  - name: 'calculate'
    unicode: 'e552'
  - name: 'bank'
    unicode: '1f3e6'
  - name: 'presentation'
    unicode: 'e57b'
  - name: 'barchart'
    unicode: '1f4ca'
  - name: 'piechart'
    unicode: 'e570'
  - name: 'activity'
    unicode: 'e57a'
  - name: 'box'
    unicode: '1f4e6'
  - name: 'home'
    unicode: '2302'
  - name: 'fence'
    unicode: 'e601'
  - name: 'buildings'
    unicode: '1f3e2'
  - name: 'lodging'
    unicode: '1f3e8'
  - name: 'globe'
    unicode: '1f310'
  - name: 'navigate'
    unicode: 'e670'
  - name: 'compass'
    unicode: 'e671'
  - name: 'signpost'
    unicode: 'e672'
  - name: 'map'
    unicode: 'e673'
  - name: 'location'
    unicode: 'e6d0'
  - name: 'pin'
    unicode: '1f4cd'
  - name: 'pushpin'
    unicode: '1f4cc'
  - name: 'code'
    unicode: 'e780'
  - name: 'puzzle'
    unicode: 'e710'
  - name: 'floppydisk'
    unicode: '1f4be'
  - name: 'window'
    unicode: 'e714'
  - name: 'music'
    unicode: '266b'
  - name: 'mic'
    unicode: '1f3a4'
  - name: 'headphones'
    unicode: '1f3a7'
  - name: 'mutevolume'
    unicode: 'e808'
  - name: 'volume'
    unicode: '1f508'
  - name: 'lowvolume'
    unicode: '1f509'
  - name: 'highvolume'
    unicode: '1f50a'
  - name: 'radio'
    unicode: '1f4fb'
  - name: 'airplay'
    unicode: 'e800'
  - name: 'disc'
    unicode: '1f4bf'
  - name: 'camera'
    unicode: '1f4f7'
  - name: 'picture'
    unicode: '1f304'
  - name: 'pictures'
    unicode: 'e851'
  - name: 'video'
    unicode: '1f4f9'
  - name: 'film'
    unicode: 'e8b0'
  - name: 'clapboard'
    unicode: '1f3ac'
  - name: 'tv'
    unicode: '1f4fa'
  - name: 'flatscreen'
    unicode: 'e8c0'
  - name: 'play'
    unicode: '25b6'
  - name: 'pause'
    unicode: 'e8a0'
  - name: 'stop'
    unicode: '25a0'
  - name: 'record'
    unicode: '25cf'
  - name: 'rewind'
    unicode: '23ea'
  - name: 'fastforward'
    unicode: '23e9'
  - name: 'skipforward'
    unicode: '23ed'
  - name: 'skipback'
    unicode: '23ee'
  - name: 'eject'
    unicode: '23cf'
  - name: 'filecabinet'
    unicode: 'e900'
  - name: 'books'
    unicode: '1f4da'
  - name: 'notebook'
    unicode: '1f4d3'
  - name: 'newspaper'
    unicode: '1f4f0'
  - name: 'grid'
    unicode: 'e9a0'
  - name: 'rows'
    unicode: 'e9a1'
  - name: 'columns'
    unicode: 'e9a2'
  - name: 'thumbnails'
    unicode: 'e9a3'
  - name: 'menu'
    unicode: 'ee06'
  - name: 'filter'
    unicode: 'e9b0'
  - name: 'desktop'
    unicode: '1f4bb'
  - name: 'laptop'
    unicode: 'ea00'
  - name: 'tablet'
    unicode: 'ea01'
  - name: 'cell'
    unicode: '1f4f1'
  - name: 'battery'
    unicode: '1f50b'
  - name: 'highbattery'
    unicode: 'ea10'
  - name: 'mediumbattery'
    unicode: 'ea11'
  - name: 'lowbattery'
    unicode: 'ea12'
  - name: 'emptybattery'
    unicode: 'ea13'
  - name: 'batterydisabled'
    unicode: 'ea15'
  - name: 'lightbulb'
    unicode: '1f4a1'
  - name: 'flashlight'
    unicode: '1f526'
  - name: 'flashlighton'
    unicode: 'ea89'
  - name: 'picnictable'
    unicode: 'eab1'
  - name: 'birdhouse'
    unicode: 'eab4'
  - name: 'lamp'
    unicode: 'ea8a'
  - name: 'onedie'
    unicode: '2680'
  - name: 'twodie'
    unicode: '2681'
  - name: 'threedie'
    unicode: '2682'
  - name: 'fourdie'
    unicode: '2683'
  - name: 'fivedie'
    unicode: '2684'
  - name: 'sixdie'
    unicode: '2685'
  - name: 'downloadcloud'
    unicode: 'eb00'
  - name: 'download'
    unicode: 'eb01'
  - name: 'uploadcloud'
    unicode: 'eb40'
  - name: 'upload'
    unicode: 'eb41'
  - name: 'transfer'
    unicode: '21c6'
  - name: 'replay'
    unicode: '21ba'
  - name: 'refresh'
    unicode: '21bb'
  - name: 'sync'
    unicode: 'eb82'
  - name: 'loading'
    unicode: 'eb83'
  - name: 'wifi'
    unicode: 'eb84'
  - name: 'file'
    unicode: '1f4c4'
  - name: 'files'
    unicode: 'ec00'
  - name: 'searchfile'
    unicode: 'ec05'
  - name: 'folder'
    unicode: '1f4c1'
  - name: 'downloadfolder'
    unicode: 'ec76'
  - name: 'uploadfolder'
    unicode: 'ec77'
  - name: 'quote'
    unicode: '201c'
  - name: 'anchor'
    unicode: 'ed10'
  - name: 'print'
    unicode: '2399'
  - name: 'fax'
    unicode: '1f4e0'
  - name: 'shredder'
    unicode: 'ed40'
  - name: 'typewriter'
    unicode: 'ed41'
  - name: 'list'
    unicode: 'ed50'
  - name: 'action'
    unicode: 'ee00'
  - name: 'redirect'
    unicode: '21aa'
  - name: 'additem'
    unicode: 'ee09'
  - name: 'checkitem'
    unicode: 'ee0b'
  - name: 'expand'
    unicode: '2922'
  - name: 'contract'
    unicode: 'ee01'
  - name: 'scaleup'
    unicode: 'ee04'
  - name: 'scaledown'
    unicode: 'ee05'
  - name: 'lifepreserver'
    unicode: 'ee11'
  - name: 'help'
    unicode: '2753'
  - name: 'info'
    unicode: '2139'
  - name: 'alert'
    unicode: '26a0'
  - name: 'caution'
    unicode: '26d4'
  - name: 'plus'
    unicode: '002b'
  - name: 'hyphen'
    unicode: '002d'
  - name: 'check'
    unicode: '2713'
  - name: 'delete'
    unicode: '2421'
  - name: 'fish'
    unicode: '1f41f'
  - name: 'bird'
    unicode: '1f426'
  - name: 'bone'
    unicode: 'ef60'
  - name: 'tooth'
    unicode: 'ef61'
  - name: 'poo'
    unicode: '1f4a9'
  - name: 'tree'
    unicode: '1f332'
  - name: 'settings'
    unicode: '2699'
  - name: 'dashboard'
    unicode: 'f000'
  - name: 'dial'
    unicode: 'f004'
  - name: 'notifications'
    unicode: '1f514'
  - name: 'notificationsdisabled'
    unicode: '1f515'
  - name: 'toggles'
    unicode: 'f001'
  - name: 'flash'
    unicode: '2301'
  - name: 'flashoff'
    unicode: 'f011'
  - name: 'magnet'
    unicode: 'f012'
  - name: 'toolbox'
    unicode: 'f030'
  - name: 'wrench'
    unicode: '1f527'
  - name: 'clock'
    unicode: '23f2'
  - name: 'stopwatch'
    unicode: '23f1'
  - name: 'alarmclock'
    unicode: '23f0'
  - name: 'counterclockwise'
    unicode: '2940'
  - name: 'calendar'
    unicode: '1f4c5'
  - name: 'keyboard'
    unicode: 'f0d2'
  - name: 'keyboardup'
    unicode: 'f0d0'
  - name: 'keyboarddown'
    unicode: 'f0d1'
  - name: 'chickenleg'
    unicode: '1f357'
  - name: 'burger'
    unicode: '1f354'
  - name: 'mug'
    unicode: '2615'
  - name: 'coffee'
    unicode: 'f120'
  - name: 'tea'
    unicode: '1f375'
  - name: 'wineglass'
    unicode: '1f377'
  - name: 'paperbag'
    unicode: 'f161'
  - name: 'utensils'
    unicode: '1f374'
  - name: 'droplet'
    unicode: '1f4a7'
  - name: 'sun'
    unicode: '2600'
  - name: 'cloud'
    unicode: '2601'
  - name: 'partlycloudy'
    unicode: '26c5'
  - name: 'umbrella'
    unicode: '2602'
  - name: 'crescentmoon'
    unicode: '1f319'
  - name: 'plug'
    unicode: '1f50c'
  - name: 'outlet'
    unicode: 'f282'
  - name: 'car'
    unicode: '1f698'
  - name: 'taxi'
    unicode: '1f696'
  - name: 'train'
    unicode: '1f686'
  - name: 'bus'
    unicode: '1f68d'
  - name: 'truck'
    unicode: '1f69a'
  - name: 'plane'
    unicode: '2708'
  - name: 'bike'
    unicode: '1f6b2'
  - name: 'rocket'
    unicode: '1f680'
  - name: 'briefcase'
    unicode: '1f4bc'
  - name: 'theatre'
    unicode: '1f3ad'
  - name: 'flask'
    unicode: 'f4c0'
  - name: 'up'
    unicode: '2b06'
  - name: 'upright'
    unicode: '2b08'
  - name: 'right'
    unicode: '27a1'
  - name: 'downright'
    unicode: '2b0a'
  - name: 'down'
    unicode: '2b07'
  - name: 'downleft'
    unicode: '2b0b'
  - name: 'left'
    unicode: '2b05'
  - name: 'upleft'
    unicode: '2b09'
  - name: 'navigateup'
    unicode: 'f500'
  - name: 'navigateright'
    unicode: '25bb'
  - name: 'navigatedown'
    unicode: 'f501'
  - name: 'navigateleft'
    unicode: '25c5'
  - name: 'share'
    unicode: 'f601'
