token: e29d6a2f
name: Social Circle
family: Social Circle
style: Regular
version: 1.0.0
filename: ss-social-circle.ttf
optimized_for: 48px
css_prefix: ss-social-circle
icon_css_prefix: ss-social-circle
website: https://www.symbolset.com/icons/social-circle
premium: true
price: 5.00
download_package: ss-social-circle.zip
active: false

designer:
  first_name: Mike
  last_name: Fortress
  email: mike@symbolset.com
  website: http://mikefortress.com

plans:
  - owner

icons:
  - name: 'facebook'
    unicode: 'f610'
  - name: 'twitter'
    unicode: 'f611'
  - name: 'googleplus'
    unicode: 'f613'
  - name: 'appdotnet'
    unicode: 'f614'
  - name: 'ello'
    unicode: 'f618'
  - name: 'aboutme'
    unicode: 'f619'
  - name: 'vk'
    unicode: 'f61a'
  - name: 'weibo'
    unicode: 'f61b'
  - name: 'linkedin'
    unicode: 'f612'
  - name: 'zerply'
    unicode: 'f615'
  - name: 'xing'
    unicode: 'f61c'
  - name: 'reddit'
    unicode: 'f616'
  - name: 'steam'
    unicode: 'f617'
  - name: 'tumblr'
    unicode: 'f620'
  - name: 'wordpress'
    unicode: 'f621'
  - name: 'blogger'
    unicode: 'f622'
  - name: 'quora'
    unicode: 'f624'
  - name: 'youtube'
    unicode: 'f630'
  - name: 'vimeo'
    unicode: 'f631'
  - name: 'vine'
    unicode: 'f633'
  - name: 'letterboxd'
    unicode: 'f632'
  - name: 'flickr'
    unicode: 'f640'
  - name: 'instagram'
    unicode: 'f641'
  - name: 'vscogrid'
    unicode: 'f643'
  - name: 'fivehundredpx'
    unicode: 'f642'
  - name: 'feedly'
    unicode: 'f656'
  - name: 'pinterest'
    unicode: 'f650'
  - name: 'dropbox'
    unicode: 'f653'
  - name: 'pinboard'
    unicode: 'f654'
  - name: 'delicious'
    unicode: 'f655'
  - name: 'dribbble'
    unicode: 'f660'
  - name: 'behance'
    unicode: 'f661'
  - name: 'github'
    unicode: 'f670'
  - name: 'bitbucket'
    unicode: 'f674'
  - name: 'stackoverflow'
    unicode: 'f672'
  - name: 'stackexchange'
    unicode: 'f673'
  - name: 'codepen'
    unicode: 'f675'
  - name: 'jsfiddle'
    unicode: 'f676'
  - name: 'paypal'
    unicode: 'f680'
  - name: 'shopify'
    unicode: 'f683'
  - name: 'kickstarter'
    unicode: 'f681'
  - name: 'etsy'
    unicode: 'f682'
  - name: 'foursquare'
    unicode: 'f690'
  - name: 'swarm'
    unicode: 'f692'
  - name: 'yelp'
    unicode: 'f691'
  - name: 'skype'
    unicode: 'f6a0'
  - name: 'whatsapp'
    unicode: 'f6a2'
  - name: 'rdio'
    unicode: 'f6b0'
  - name: 'spotify'
    unicode: 'f6b1'
  - name: 'lastfm'
    unicode: 'f6b2'
  - name: 'soundcloud'
    unicode: 'f6b3'
  - name: 'appstore'
    unicode: 'f6fa'
  - name: 'googleplay'
    unicode: 'f6fb'
  - name: 'appleinc'
    unicode: 'f8ff'
  - name: 'microsoft'
    unicode: 'f6f1'
  - name: 'windows'
    unicode: 'f6f2'
  - name: 'android'
    unicode: 'f6f3'
  - name: 'blackberry'
    unicode: 'f6f4'
  - name: 'link'
    unicode: '1f517'
  - name: 'phone'
    unicode: '1f4de'
  - name: 'mail'
    unicode: '2709'
  - name: 'like'
    unicode: '1f44d'
  - name: 'rss'
    unicode: 'e310'
  - name: 'share'
    unicode: 'f601'
