token: bb881356
name: Standard
family: Standard
style: Regular
version: 1.0.0
filename: ss-standard.ttf
optimized_for: 16px
css_prefix: ss-standard
icon_css_prefix: ss-standard
website: https://symbolset.com/icons/standard
premium: true
price: 30.00
download_package: ss-standard.zip

designer:
  first_name: Mike
  last_name: Fortress
  email: mike@symbolset.com
  website: http://mikefortress.com

plans:
  - owner

icons:
  - name: 'cursor'
    unicode: 'e001'
  - name: 'crosshair'
    unicode: '2316'
  - name: 'search'
    unicode: '1f50e'
  - name: 'zoomin'
    unicode: 'e002'
  - name: 'zoomout'
    unicode: 'e003'
  - name: 'view'
    unicode: '1f440'
  - name: 'attach'
    unicode: '1f4ce'
  - name: 'link'
    unicode: '1f517'
  - name: 'move'
    unicode: 'e070'
  - name: 'write'
    unicode: '270e'
  - name: 'writingdisabled'
    unicode: 'e071'
  - name: 'erase'
    unicode: '2710'
  - name: 'compose'
    unicode: '1f4dd'
  - name: 'lock'
    unicode: '1f512'
  - name: 'unlock'
    unicode: '1f513'
  - name: 'key'
    unicode: '1f511'
  - name: 'backspace'
    unicode: '232b'
  - name: 'ban'
    unicode: '1f6ab'
  - name: 'trash'
    unicode: 'e0d0'
  - name: 'target'
    unicode: '25ce'
  - name: 'tag'
    unicode: 'e100'
  - name: 'bookmark'
    unicode: '1f516'
  - name: 'flag'
    unicode: '2691'
  - name: 'like'
    unicode: '1f44d'
  - name: 'dislike'
    unicode: '1f44e'
  - name: 'heart'
    unicode: '2665'
  - name: 'halfheart'
    unicode: 'e1a0'
  - name: 'star'
    unicode: '22c6'
  - name: 'halfstar'
    unicode: 'e1a1'
  - name: 'sample'
    unicode: 'e200'
  - name: 'crop'
    unicode: 'e201'
  - name: 'layers'
    unicode: 'e202'
  - name: 'fill'
    unicode: 'e240'
  - name: 'stroke'
    unicode: 'e241'
  - name: 'phone'
    unicode: '1f4de'
  - name: 'phonedisabled'
    unicode: 'e300'
  - name: 'rss'
    unicode: 'e310'
  - name: 'facetime'
    unicode: 'e320'
  - name: 'reply'
    unicode: '21a9'
  - name: 'send'
    unicode: 'e350'
  - name: 'mail'
    unicode: '2709'
  - name: 'inbox'
    unicode: '1f4e5'
  - name: 'chat'
    unicode: '1f4ac'
  - name: 'ellipsischat'
    unicode: 'e399'
  - name: 'ellipsis'
    unicode: '2026'
  - name: 'user'
    unicode: '1f464'
  - name: 'femaleuser'
    unicode: '1f467'
  - name: 'users'
    unicode: '1f465'
  - name: 'cart'
    unicode: 'e500'
  - name: 'creditcard'
    unicode: '1f4b3'
  - name: 'dollarsign'
    unicode: '1f4b2'
  - name: 'barchart'
    unicode: '1f4ca'
  - name: 'piechart'
    unicode: 'e570'
  - name: 'box'
    unicode: '1f4e6'
  - name: 'home'
    unicode: '2302'
  - name: 'buildings'
    unicode: '1f3e2'
  - name: 'warehouse'
    unicode: 'e602'
  - name: 'globe'
    unicode: '1f30e'
  - name: 'navigate'
    unicode: 'e670'
  - name: 'compass'
    unicode: 'e671'
  - name: 'signpost'
    unicode: 'e672'
  - name: 'map'
    unicode: 'e673'
  - name: 'location'
    unicode: 'e6d0'
  - name: 'pin'
    unicode: '1f4cd'
  - name: 'database'
    unicode: 'e7a0'
  - name: 'hdd'
    unicode: 'e7b0'
  - name: 'music'
    unicode: '266b'
  - name: 'mic'
    unicode: '1f3a4'
  - name: 'volume'
    unicode: '1f508'
  - name: 'lowvolume'
    unicode: '1f509'
  - name: 'highvolume'
    unicode: '1f50a'
  - name: 'airplay'
    unicode: 'e800'
  - name: 'camera'
    unicode: '1f4f7'
  - name: 'picture'
    unicode: '1f304'
  - name: 'video'
    unicode: '1f4f9'
  - name: 'play'
    unicode: '25b6'
  - name: 'pause'
    unicode: 'e8a0'
  - name: 'stop'
    unicode: '25a0'
  - name: 'record'
    unicode: '25cf'
  - name: 'rewind'
    unicode: '23ea'
  - name: 'fastforward'
    unicode: '23e9'
  - name: 'skipback'
    unicode: '23ee'
  - name: 'skipforward'
    unicode: '23ed'
  - name: 'eject'
    unicode: '23cf'
  - name: 'repeat'
    unicode: '1f501'
  - name: 'replay'
    unicode: '21ba'
  - name: 'shuffle'
    unicode: '1f500'
  - name: 'book'
    unicode: '1f4d5'
  - name: 'openbook'
    unicode: '1f4d6'
  - name: 'notebook'
    unicode: '1f4d3'
  - name: 'newspaper'
    unicode: '1f4f0'
  - name: 'grid'
    unicode: 'e9a0'
  - name: 'rows'
    unicode: 'e9a1'
  - name: 'columns'
    unicode: 'e9a2'
  - name: 'thumbnails'
    unicode: 'e9a3'
  - name: 'filter'
    unicode: 'e9b0'
  - name: 'desktop'
    unicode: '1f4bb'
  - name: 'laptop'
    unicode: 'ea00'
  - name: 'tablet'
    unicode: 'ea01'
  - name: 'cell'
    unicode: '1f4f1'
  - name: 'battery'
    unicode: '1f50b'
  - name: 'highbattery'
    unicode: 'ea10'
  - name: 'mediumbattery'
    unicode: 'ea11'
  - name: 'lowbattery'
    unicode: 'ea12'
  - name: 'emptybattery'
    unicode: 'ea13'
  - name: 'lightbulb'
    unicode: '1f4a1'
  - name: 'downloadcloud'
    unicode: 'eb00'
  - name: 'download'
    unicode: 'eb01'
  - name: 'uploadcloud'
    unicode: 'eb40'
  - name: 'upload'
    unicode: 'eb41'
  - name: 'fork'
    unicode: 'eb80'
  - name: 'merge'
    unicode: 'eb81'
  - name: 'transfer'
    unicode: '21c6'
  - name: 'refresh'
    unicode: '21bb'
  - name: 'sync'
    unicode: 'eb82'
  - name: 'loading'
    unicode: 'eb83'
  - name: 'wifi'
    unicode: 'eb84'
  - name: 'connection'
    unicode: 'eb85'
  - name: 'file'
    unicode: '1f4c4'
  - name: 'folder'
    unicode: '1f4c1'
  - name: 'quote'
    unicode: '201c'
  - name: 'text'
    unicode: 'ed00'
  - name: 'font'
    unicode: 'ed01'
  - name: 'print'
    unicode: '2399'
  - name: 'fax'
    unicode: '1f4e0'
  - name: 'list'
    unicode: 'ed50'
  - name: 'layout'
    unicode: 'eda0'
  - name: 'action'
    unicode: 'ee00'
  - name: 'redirect'
    unicode: '21aa'
  - name: 'expand'
    unicode: '2922'
  - name: 'contract'
    unicode: 'ee01'
  - name: 'help'
    unicode: '2753'
  - name: 'info'
    unicode: '2139'
  - name: 'alert'
    unicode: '26a0'
  - name: 'caution'
    unicode: '26d4'
  - name: 'logout'
    unicode: 'ee02'
  - name: 'plus'
    unicode: '002b'
  - name: 'hyphen'
    unicode: '002d'
  - name: 'check'
    unicode: '2713'
  - name: 'delete'
    unicode: '2421'
  - name: 'settings'
    unicode: '2699'
  - name: 'dashboard'
    unicode: 'f000'
  - name: 'notifications'
    unicode: '1f514'
  - name: 'notificationsdisabled'
    unicode: '1f515'
  - name: 'clock'
    unicode: '23f2'
  - name: 'stopwatch'
    unicode: '23f1'
  - name: 'calendar'
    unicode: '1f4c5'
  - name: 'addcalendar'
    unicode: 'f070'
  - name: 'removecalendar'
    unicode: 'f071'
  - name: 'checkcalendar'
    unicode: 'f072'
  - name: 'deletecalendar'
    unicode: 'f073'
  - name: 'plane'
    unicode: '2708'
  - name: 'briefcase'
    unicode: '1f4bc'
  - name: 'cloud'
    unicode: '2601'
  - name: 'droplet'
    unicode: '1f4a7'
  - name: 'flask'
    unicode: 'f4c0'
  - name: 'up'
    unicode: '2b06'
  - name: 'upright'
    unicode: '2b08'
  - name: 'right'
    unicode: '27a1'
  - name: 'downright'
    unicode: '2b0a'
  - name: 'down'
    unicode: '2b07'
  - name: 'downleft'
    unicode: '2b0b'
  - name: 'left'
    unicode: '2b05'
  - name: 'upleft'
    unicode: '2b09'
  - name: 'navigateup'
    unicode: 'f500'
  - name: 'navigateright'
    unicode: '25bb'
  - name: 'navigatedown'
    unicode: 'f501'
  - name: 'navigateleft'
    unicode: '25c5'
  - name: 'directup'
    unicode: '25b4'
  - name: 'directright'
    unicode: '25b9'
  - name: 'dropdown'
    unicode: '25be'
  - name: 'directleft'
    unicode: '25c3'
  - name: 'retweet'
    unicode: 'f600'

