token: e30b028c
name: Steedicons
family: Steedicons
style: Regular
version: 1.0.0
filename: ss-steedicons.ttf
optimized_for: 32px
css_prefix: ss-steedicons
icon_css_prefix: ss-steedicons
website: https://symbolset.com/icons/steedicons
premium: true
price: 40.00
download_package: ss-steedicons.zip
active: false

designer:
  first_name: Kyle
  last_name: Steed
  email: hello@kylesteed.com
  website: http://www.kylesteed.com

plans:
  - owner

icons:
  - name: 'search'
    unicode: '1f50e'
  - name: 'view'
    unicode: '1f440'
  - name: 'attach'
    unicode: '1f4ce'
  - name: 'move'
    unicode: 'e070'
  - name: 'write'
    unicode: '270e'
  - name: 'lock'
    unicode: '1f512'
  - name: 'unlock'
    unicode: '1f513'
  - name: 'ban'
    unicode: '1f6ab'
  - name: 'trash'
    unicode: 'e0d0'
  - name: 'target'
    unicode: '25ce'
  - name: 'skull'
    unicode: '1f480'
  - name: 'lightning'
    unicode: '2607'
  - name: 'tag'
    unicode: 'e100'
  - name: 'bookmark'
    unicode: '1f516'
  - name: 'like'
    unicode: '1f44d'
  - name: 'dislike'
    unicode: '1f44e'
  - name: 'heart'
    unicode: '2665'
  - name: 'emptyheart'
    unicode: '2661'
  - name: 'star'
    unicode: '22c6'
  - name: 'emptystar'
    unicode: '2606'
  - name: 'glowingstar'
    unicode: '1f31f'
  - name: 'shield'
    unicode: 'e012'
  - name: 'magicwand'
    unicode: 'e203'
  - name: 'pencilspen'
    unicode: 'e227'
  - name: 'clipboard'
    unicode: '1f4cb'
  - name: 'checkclipboard'
    unicode: 'e2b3'
  - name: 'rules'
    unicode: '1f4cf'
  - name: 'feather'
    unicode: 'e220'
  - name: 'ink'
    unicode: 'e228'
  - name: 'phone'
    unicode: '1f4de'
  - name: 'rss'
    unicode: 'e310'
  - name: 'mail'
    unicode: '2709'
  - name: 'inbox'
    unicode: '1f4e5'
  - name: 'outbox'
    unicode: '1f4e4'
  - name: 'chat'
    unicode: '1f4ac'
  - name: 'chats'
    unicode: 'e390'
  - name: 'ampersand'
    unicode: '0026'
  - name: 'exclamation'
    unicode: '0021'
  - name: 'question'
    unicode: '003f'
  - name: 'manwink'
    unicode: 'e3b0'
  - name: 'womanwink'
    unicode: 'e3b1'
  - name: 'user'
    unicode: '1f464'
  - name: 'adduser'
    unicode: 'e401'
  - name: 'removeuser'
    unicode: 'e402'
  - name: 'downloaduser'
    unicode: 'e40a'
  - name: 'uploaduser'
    unicode: 'e40b'
  - name: 'addusers'
    unicode: 'e411'
  - name: 'usergroup'
    unicode: 'e400'
  - name: 'businessuser'
    unicode: 'e407'
  - name: 'capuser'
    unicode: 'e408'
  - name: 'cowboyuser'
    unicode: 'e409'
  - name: 'man'
    unicode: '1f468'
  - name: 'woman'
    unicode: '1f469'
  - name: 'maleprofileleft'
    unicode: 'e460'
  - name: 'maleprofileright'
    unicode: 'e461'
  - name: 'femaleprofileleft'
    unicode: 'e462'
  - name: 'femaleprofileright'
    unicode: 'e463'
  - name: 'raisedhand'
    unicode: '270b'
  - name: 'mouth'
    unicode: '1f444'
  - name: 'mustache'
    unicode: 'e431'
  - name: 'robot'
    unicode: 'e440'
  - name: 'userprofile'
    unicode: 'e406'
  - name: 'contacts'
    unicode: '1f4c7'
  - name: 'addressbook'
    unicode: '1f4d1'
  - name: 'cart'
    unicode: 'e500'
  - name: 'shoppingbag'
    unicode: 'e520'
  - name: 'gift'
    unicode: '1f381'
  - name: 'creditcard'
    unicode: '1f4b3'
  - name: 'banknote'
    unicode: '1f4b5'
  - name: 'dollarsign'
    unicode: '0024'
  - name: 'poundsign'
    unicode: '00a3'
  - name: 'eurosign'
    unicode: '20ac'
  - name: 'yensign'
    unicode: '00a5'
  - name: 'piechart'
    unicode: 'e570'
  - name: 'piechartthirds'
    unicode: 'e571'
  - name: 'barchart'
    unicode: '1f4ca'
  - name: 'activity'
    unicode: 'e57a'
  - name: 'upwardslinechart'
    unicode: '1f4c8'
  - name: 'downwardslinechart'
    unicode: '1f4c9'
  - name: 'box'
    unicode: '1f4e6'
  - name: 'crate'
    unicode: 'e5d8'
  - name: 'home'
    unicode: '2302'
  - name: 'warehouse'
    unicode: 'e602'
  - name: 'globe'
    unicode: '1f30e'
  - name: 'map'
    unicode: 'e673'
  - name: 'location'
    unicode: 'e6d0'
  - name: 'pin'
    unicode: '1f4cd'
  - name: 'floppydisk'
    unicode: '1f4be'
  - name: 'code'
    unicode: 'e780'
  - name: 'commandline'
    unicode: 'e781'
  - name: 'window'
    unicode: 'e714'
  - name: 'searchwindow'
    unicode: 'e715'
  - name: 'downloadhdd'
    unicode: 'e7b7'
  - name: 'uploadhdd'
    unicode: 'e7b8'
  - name: 'command'
    unicode: '2318'
  - name: 'music'
    unicode: '266b'
  - name: 'mic'
    unicode: '1f3a4'
  - name: 'micdisabled'
    unicode: 'e804'
  - name: 'ipod'
    unicode: 'ea06'
  - name: 'recordplayer'
    unicode: 'e805'
  - name: 'headphones'
    unicode: '1f3a7'
  - name: 'radio'
    unicode: '1f4fb'
  - name: 'disc'
    unicode: '1f4bf'
  - name: 'cassette'
    unicode: 'e806'
  - name: 'camera'
    unicode: '1f4f7'
  - name: 'addcamera'
    unicode: 'e861'
  - name: 'picture'
    unicode: '1f304'
  - name: 'video'
    unicode: '1f4f9'
  - name: 'playfilm'
    unicode: 'e8b1'
  - name: 'playvideo'
    unicode: 'e8a1'
  - name: 'hd'
    unicode: 'e830'
  - name: 'dvd'
    unicode: 'e831'
  - name: 'videogame'
    unicode: '1f3ae'
  - name: 'cartridge'
    unicode: 'ea43'
  - name: 'play'
    unicode: '25b6'
  - name: 'pause'
    unicode: 'e8a0'
  - name: 'stop'
    unicode: '25a0'
  - name: 'record'
    unicode: '25cf'
  - name: 'rewind'
    unicode: '23ea'
  - name: 'fastforward'
    unicode: '23e9'
  - name: 'eject'
    unicode: '23cf'
  - name: 'replay'
    unicode: '21ba'
  - name: 'notebook'
    unicode: '1f4d3'
  - name: 'ledger'
    unicode: '1f4d2'
  - name: 'sketchbook'
    unicode: 'e974'
  - name: 'album'
    unicode: 'e970'
  - name: 'grid'
    unicode: 'e9a0'
  - name: 'rows'
    unicode: 'e9a1'
  - name: 'mouse'
    unicode: 'ea40'
  - name: 'desktop'
    unicode: '1f4bb'
  - name: 'cell'
    unicode: '1f4f1'
  - name: 'battery'
    unicode: '1f50b'
  - name: 'mediumbattery'
    unicode: 'ea11'
  - name: 'lowbattery'
    unicode: 'ea12'
  - name: 'frame'
    unicode: 'ea90'
  - name: 'download'
    unicode: 'eb01'
  - name: 'upload'
    unicode: 'eb41'
  - name: 'merge'
    unicode: 'eb81'
  - name: 'transfer'
    unicode: '21c6'
  - name: 'file'
    unicode: '1f4c4'
  - name: 'files'
    unicode: 'ec00'
  - name: 'checkfile'
    unicode: 'ec03'
  - name: 'folder'
    unicode: '1f4c1'
  - name: 'openfolder'
    unicode: '1f4c2'
  - name: 'font'
    unicode: 'ed01'
  - name: 'print'
    unicode: '2399'
  - name: 'expand'
    unicode: '2922'
  - name: 'help'
    unicode: '2753'
  - name: 'info'
    unicode: '2139'
  - name: 'alert'
    unicode: '26a0'
  - name: 'plus'
    unicode: '002b'
  - name: 'hyphen'
    unicode: '002d'
  - name: 'check'
    unicode: '2713'
  - name: 'delete'
    unicode: '2421'
  - name: 'dog'
    unicode: '1f415'
  - name: 'pandaface'
    unicode: '1f43c'
  - name: 'mouseface'
    unicode: '1f42d'
  - name: 'dear'
    unicode: 'ef00'
  - name: 'settings'
    unicode: '2699'
  - name: 'dashboard'
    unicode: 'f000'
  - name: 'brightness'
    unicode: '1f506'
  - name: 'wrench'
    unicode: '1f527'
  - name: 'hammer'
    unicode: '1f528'
  - name: 'clock'
    unicode: '23f2'
  - name: 'calendar'
    unicode: '1f4c5'
  - name: 'keyboard'
    unicode: 'f0d2'
  - name: 'sushi'
    unicode: 'f108'
  - name: 'burger'
    unicode: '1f354'
  - name: 'bread'
    unicode: '1f35e'
  - name: 'frenchfries'
    unicode: '1f35f'
  - name: 'cupcake'
    unicode: 'f118'
  - name: 'apple'
    unicode: '1f34f'
  - name: 'mug'
    unicode: '2615'
  - name: 'coffee'
    unicode: 'f120'
  - name: 'latte'
    unicode: 'eff3'
  - name: 'soda'
    unicode: 'f124'
  - name: 'sodacan'
    unicode: 'f12c'
  - name: 'cup'
    unicode: 'f125'
  - name: 'utensils'
    unicode: '1f374'
  - name: 'chopsticks'
    unicode: 'f154'
  - name: 'cap'
    unicode: 'f1b0'
  - name: 'cowboyhat'
    unicode: 'f1b1'
  - name: 'glasses'
    unicode: '1f453'
  - name: 'tshirt'
    unicode: '1f455'
  - name: 'sock'
    unicode: 'f1b4'
  - name: 'shoe'
    unicode: '1f45f'
  - name: 'briefcase'
    unicode: '1f4bc'
  - name: 'suitcase'
    unicode: 'e420'
  - name: 'backpack'
    unicode: '1f392'
  - name: 'cloud'
    unicode: '2601'
  - name: 'sun'
    unicode: '2600'
  - name: 'rain'
    unicode: '2614'
  - name: 'rainbow'
    unicode: '1f308'
  - name: 'tree'
    unicode: '1f333'
  - name: 'evergreen'
    unicode: '1f332'
  - name: 'leaf'
    unicode: '1f342'
  - name: 'wave'
    unicode: '1f30a'
  - name: 'mountains'
    unicode: '26f0'
  - name: 'gem'
    unicode: '1f48e'
  - name: 'truck'
    unicode: '1f69a'
  - name: 'highway'
    unicode: 'f320'
  - name: 'roads'
    unicode: 'f326'
  - name: 'skateboard'
    unicode: 'f409'
  - name: 'rollerskate'
    unicode: 'f40a'
  - name: 'right'
    unicode: '27a1'
  - name: 'left'
    unicode: '2b05'
  - name: 'circle'
    unicode: '25cb'
  - name: 'triangle'
    unicode: '25b2'
  - name: 'emptytriangle'
    unicode: '25b3'
  - name: 'dottedtriangle'
    unicode: 'f550'
  - name: 'emptyburst'
    unicode: 'f551'
  - name: 'cross'
    unicode: '271d'
  - name: 'one'
    unicode: '0031'
  - name: 'retweet'
    unicode: 'f600'
  - name: 'facebook'
    unicode: 'f610'
  - name: 'twitter'
    unicode: 'f611'
  - name: 'tumblr'
    unicode: 'f620'
  - name: 'wordpress'
    unicode: 'f621'
  - name: 'blogger'
    unicode: 'f622'
  - name: 'vimeo'
    unicode: 'f631'
  - name: 'flickr'
    unicode: 'f640'
  - name: 'dropbox'
    unicode: 'f653'
  - name: 'dribbble'
    unicode: 'f660'
  - name: 'github'
    unicode: 'f670'
  - name: 'paypal'
    unicode: 'f680'
  - name: 'skype'
    unicode: 'f6a0'
  - name: 'rdio'
    unicode: 'f6b0'
  - name: 'lastfm'
    unicode: 'f6b2'
  - name: 'mailchimp'
    unicode: 'f6a1'
  - name: 'appleinc'
    unicode: 'f8ff'
  - name: 'microsoft'
    unicode: 'f6f1'
  - name: 'google'
    unicode: 'f6f5'
  - name: 'safari'
    unicode: 'f6f6'
  - name: 'chrome'
    unicode: 'f6f7'
  - name: 'firefox'
    unicode: 'f6f8'
  - name: 'appstore'
    unicode: 'f6fa'
  - name: 'psd'
    unicode: 'f6e0'
  - name: 'ai'
    unicode: 'f6e1'
  - name: 'indd'
    unicode: 'f6e2'
  - name: 'pdf'
    unicode: 'ec34'
  - name: 'lr'
    unicode: 'f6e3'
  - name: 'fla'
    unicode: 'f6e4'
  - name: 'fw'
    unicode: 'f6e5'
